#import "../preamble.typ": source-statutes-plus-table, source-statutes-cell, source-statutes-dual-cell, h2
#h2([A. Copyright Ordinance (Cap.528)])
#source-statutes-plus-table(
  [*Section*],
  [*Text*],
  [*Notes*],

  "s.100",
  source-statutes-dual-cell("100. 对作品的部分适用的条文(1)第89条(被识别为作者或导演的权利)所赋予的权利就作品的整项或其任何实质部分而适用。 (2)第92条(反对作品受贬损处理的权利)所赋予的权利以及第96条(虚假署名)所赋予的权利，均就作品的整项或其任何部分而适用。 [比照 1988 c. 48 s. 89 U.K.]", "100. Application of provisions to parts of works (1) The right conferred by section 89 (right to be identified as author or director) applies in relation to the whole or any substantial part of a work. (2) The rights conferred by section 92 (right to object to derogatory treatment of work) and section 96 (false attribution) apply in relation to the whole or any part of a work. [cf. 1988 c. 48 s. 89 U.K.]"),
  source-statutes-cell("有些精神权利不只管“整件作品”，对实质部分同样适用。"),

  "s.103",
  source-statutes-dual-cell("103. 专用特许(1)在本部中， 专用特许(exclusive licence)指由版权拥有人签署或由他人代其签署的书面特许，授权特许持有人在摒除所有其他人(包括批出该特许的人)的情况下行使本应属该版权拥有人可行使的独有权利。 (2)在专用特许下的特许持有人所具有的相对于受特许约束的所有权继承人而言的权利，与其所具有的相对于批出该特许的人而言的权利相同。 [比照 1988 c. 48 s. 92 U.K.]", "103. Exclusive licences (1) In this Part an exclusive licence (专用特许) means a licence in writing signed by or on behalf of the copyright owner authorizing the licensee to the exclusion of all other persons, including the person granting the licence, to exercise a right which would otherwise be exercisable exclusively by the copyright owner. (2) The licensee under an exclusive licence has the same rights against a successor in title who is bound by the licence as he has against the person granting the licence. [cf. 1988 c. 48 s. 92 U.K.]"),
  source-statutes-cell("“专用特许”本质是排他授权，范围内别人（含权利人）都不能再用。"),

  "s.107",
  source-statutes-dual-cell("107. 版权拥有人可就侵犯版权提起诉讼(1)版权拥有人可就侵犯版权提起诉讼。 (2)在就侵犯版权进行的诉讼中，原告人可得损害赔偿、强制令、交出利润或其他形式的济助，与就侵犯任何其他产权而可得者相同。 (3)本条在本分部的以下条文的规限下具有效力。 [比照 1988 c. 48 s. 96 U.K.]", "107. Infringement actionable by copyright owner (1) An infringement of copyright is actionable by the copyright owner. (2) In an action for infringement of copyright all such relief by way of damages, injunctions, accounts or otherwise is available to the plaintiff as is available in respect of the infringement of any other property right. (3) This section has effect subject to the following provisions of this Division. [cf. 1988 c. 48 s. 96 U.K.]"),
  source-statutes-cell("版权人可以就侵权起诉，常见救济包括赔偿和禁令。"),

  "s.108",
  source-statutes-dual-cell("108. 关于侵犯版权诉讼中的损害赔偿的规定(1)在就侵犯版权进行的诉讼中，如证明在侵犯版权时，被告人不知道和没有理由相信该诉讼所关乎的作品有版权存在，则原告人无权向被告人要求损害赔偿，但任何其他补救则不受影响。 (2)在就侵犯版权进行的诉讼中，法院在顾及案件的所有情况，尤其是以下情况后——(a)该等权利受侵犯的昭彰程度； (b)因侵犯版权行为而归于被告人的利益； (由 2022年第16号第61条修订) (c)被告人的业务帐目和纪录的完整程度、准确程度及可靠程度； (由 2022年第16号第61条修订) (d)构成该项侵犯的作为发生后，被告人的任何不合理行为，包括在原告人将该项侵犯告知被告人后，被告人作出的(或企图作出的)毁灭、隐藏或掩饰该项侵犯的证据的作为；及(由 2022年第16号第61条增补) (e)由于该项侵犯而令侵犯版权复制品广泛流传的可能性， (由 2022年第16号第61条增补)可为在该案件达致公正所需而判给额外损害赔偿。 [比照 1988 c. 48 s. 97 U.K.]", "108. Provisions as to damages in infringement action (1) Where in an action for infringement of copyright it is shown that at the time of the infringement the defendant did not know, and had no reason to believe, that copyright subsisted in the work to which the action relates, the plaintiff is not entitled to damages against him, but without prejudice to any other remedy. (2) The court may in an action for infringement of copyright having regard to all the circumstances, and in particular to— (a) the flagrancy of the infringement; (b) any benefit accruing to the defendant by reason of the infringement; (Amended 16 of 2022 s. 61) (c) the completeness, accuracy and reliability of the defendant’s business accounts and records; (Amended 16 of 2022 s. 61) (d) any unreasonable conduct of the defendant after the act constituting the infringement occurred, including any act done or attempt made by the defendant to destroy, conceal or disguise evidence of the infringement after having been informed of the infringement by the plaintiff; and (Added 16 of 2022 s. 61) (e) the likelihood of widespread circulation of infringing copies as a result of the infringement, (Added 16 of 2022 s. 61) award such additional damages as the justice of the case may require. [cf. 1988 c. 48 s. 97 U.K.]"),
  source-statutes-cell("算赔偿时，法院会看主观恶意、获利、证据破坏等因素。"),

  "s.112",
  source-statutes-dual-cell("112. 专用特许持有人的权利和补救(1)专用特许持有人就特许批出之后所发生的事项，具有在犹如该项特许是一项转让的情况下相同的权利和补救，但相对于版权拥有人而言，则属例外。 (2)专用特许持有人的权利和补救与版权拥有人的权利和补救是同时具有的；而在本部的有关条文中，凡提述版权拥有人，亦据此解释。 (3)在专用特许持有人凭借本条而提起的诉讼中，被告人可引用的免责辩护，与在假使该诉讼是版权的拥有人提起的情况下被告人可引用的免责辩护相同。 [比照 1988 c. 48 s. 101 U.K.]", "112. Rights and remedies of exclusive licensee (1) An exclusive licensee has, except against the copyright owner, the same rights and remedies in respect of matters occurring after the grant of the licence as if the licence had been an assignment. (2) His rights and remedies are concurrent with those of the copyright owner; and references in the relevant provisions of this Part to the copyright owner shall be construed accordingly. (3) In an action brought by an exclusive licensee by virtue of this section a defendant may avail himself of any defence which would have been available to him if the action had been brought by the copyright owner. [cf. 1988 c. 48 s. 101 U.K.]"),
  source-statutes-cell("专用被许可人也有较强的维权权能，不一定只能靠版权人出面。"),

  "s.117",
  source-statutes-dual-cell("117. 与有政府版权的作品有关的推定如文学作品、戏剧作品或音乐作品有政府版权存在，并且该作品的已刊印复制品上附有一项陈述，述明该作品作首次商业发表的年份，则在凭借本分部就该作品而提起的法律程序中，该项陈述可获接纳为所述明事实的证据，并且在没有相反证据的情况下，该项陈述须推定为正确的。 [比照 1988 c. 48 s. 106 U.K.]", "117. Presumptions relevant to works subject to Government copyright In proceedings brought by virtue of this Division with respect to a literary, dramatic or musical work in which Government copyright subsists, where there appears on printed copies of the work a statement of the year in which the work was first published commercially, that statement is admissible as evidence of the fact stated and is presumed to be correct in the absence of evidence to the contrary. [cf. 1988 c. 48 s. 106 U.K.]"),
  source-statutes-cell("有政府版权时，作品上的年份声明可当初步证据。"),

  "s.118",
  source-statutes-dual-cell("118. 关乎制作侵犯版权物品等或进行侵犯版权物品等交易的罪行(由 2007年第15号第31条修订) (1)任何人如未获版权作品(该作品)的版权拥有人的特许而作出以下作为，即属犯罪——(a)制作该作品的侵犯版权复制品，以作出售或出租之用； (b)将该作品的侵犯版权复制品输入香港，但并非供他私人和家居使用； (c)将该作品的侵犯版权复制品输出香港，但并非供他私人和家居使用； (d)为任何贸易或业务的目的或在任何贸易或业务的过程中，出售、出租、或要约出售或要约出租或为出售或出租而展示该作品的侵犯版权复制品； (e)为任何包含经销版权作品的侵犯版权复制品的贸易或业务的目的或在任何该等贸易或业务的过程中，公开陈列或分发该作品的侵犯版权复制品； (f)管有该作品的侵犯版权复制品，以期令——(i)某人可为任何贸易或业务的目的或在任何贸易或业务的过程中，出售或出租该侵犯版权复制品；或(ii)某人可为任何包含经销版权作品的侵犯版权复制品的贸易或业务的目的或在任何该等贸易或业务的过程中，公开陈列或分发该侵犯版权复制品；或(g)分发该作品的侵犯版权复制品(但并非为任何包含经销版权作品的侵犯版权复制品的贸易或业务的目的，亦并非在任何该等贸易或业务的过程中分发)，达到损害版权拥有人的权利的程度。 (由 2007年第15号第31条代替) (1A)凡——(a)任何人为任何贸易或业务的目的或在任何贸易或业务的过程中，公开陈列或分发版权作品的侵犯版权复制品；而(b)如此陈列或分发该侵犯版权复制品的情况，令人合理地怀疑该贸易或业务包含经销版权作品的侵犯版权复制品， 则就任何根据第(1)(e)款提起的法律程序而言，除非有相反的证据，否则该贸易或业务须被推定为包含经销版权作品的侵犯版权复制品的贸易或业务。 (由 2007年第15号第31条增补) (1B)凡——(a)任何人管有版权作品的侵犯版权复制品，以期令某人可为任何贸易或业务的目的或在任何贸易或业务的过程中，公开陈列或分发该侵犯版权复制品；而(b)如此管有该侵犯版权复制品的情况，令人合理地怀疑该贸易或业务包含经销版权作品的侵犯版权复制品， 则就任何根据第(1)(f)(ii)款提起的法律程序而言，除非有相反的证据，否则该贸易或业务须被推定为包含经销版权作品的侵犯版权复制品的贸易或业务。 (由 2007年第15号第31条增补) (2)第(1)(b)及(c)及(4)(b)及(c)款并不适用于过境物品。 (2AA)就第(1)(g)款而言，法院在裁定某作品的侵犯版权复制品的分发有否达到损害版权拥有人的权利的程度时——(a)可考虑有关个案的整体情况；并(b)尤其可考虑该项分发的后果，是否对版权拥有人造成经济损害，在考虑时，可顾及经如此分发的侵犯版权复制品，是否构成该作品的替代品。 (由 2022年第16号第63条增补) (2A)任何人如未获本款适用的版权作品的版权拥有人的特许，而为任何贸易或业务的目的或在任何贸易或业务的过程中，管有该作品的侵犯版权复制品，以期令某人可为该贸易或业务的目的或在该贸易或业务的过程中，使用该侵犯版权复制品，该首述的人即属犯罪。 (由 2007年第15号第31条增补) (2B)第(2A)款适用于属以下项目的版权作品——(a)电脑程式； (b)电影； (c)电视剧或电视电影； (d)音乐声音纪录；或(e)音乐视像纪录...", "118. Offences in relation to making or dealing with infringing articles, etc. (Amended 15 of 2007 s. 31) (1) A person commits an offence if he, without the licence of the copyright owner of a copyright work— (a) makes for sale or hire an infringing copy of the work; (b) imports an infringing copy of the work into Hong Kong otherwise than for his private and domestic use; (c) exports an infringing copy of the work from Hong Kong otherwise than for his private and domestic use; (d) sells, lets for hire, or offers or exposes for sale or hire an infringing copy of the work for the purpose of or in the course of any trade or business; (e) exhibits in public or distributes an infringing copy of the work for the purpose of or in the course of any trade or business which consists of dealing in infringing copies of copyright works; (f) possesses an infringing copy of the work with a view to— (i) its being sold or let for hire by any person for the purpose of or in the course of any trade or business; or (ii) its being exhibited in public or distributed by any person for the purpose of or in the course of any trade or business which consists of dealing in infringing copies of copyright works; or (g) distributes an infringing copy of the work (otherwise than for the purpose of or in the course of any trade or business which consists of dealing in infringing copies of copyright works) t..."),
  source-statutes-cell("刑事重灾区条款：制作/进口/分发侵权复制品可触发刑责。"),

  "s.12",
  source-statutes-dual-cell("12. 合作作品(1)在本部中， 合作作品(work of joint authorship)指2名或多于2名作者合作制作的作品，而各名作者的贡献是不能明显地与另一或其他作者的贡献分开的。 (2)除非任何影片的制作人和主要导演均属同一人，否则该影片须视为合作作品。 (3)如某广播是视为由多于一人作出的，则该广播须视为合作作品(第8(3)条)。 (4)在本部中，凡提述作品的作者，则就合作作品而言，须解释为提述该作品的全部作者，但另有规定的除外。 [比照 1988 c. 48 s. 10 U.K.]", "12. Works of joint authorship (1) In this Part a work of joint authorship (合作作品) means a work made by the collaboration of 2 or more authors in which the contribution of each author is not distinct from that of the other author or authors. (2) A film is treated as a work of joint authorship unless the producer and the principal director are the same person. (3) A broadcast is treated as a work of joint authorship in a case where more than one person is to be taken as making the broadcast (section 8(3)). (4) References in this Part to the author of a work are, except as otherwise provided, construed in relation to a work of joint authorship as references to all the authors of the work. [cf. 1988 c. 48 s. 10 U.K.]"),
  source-statutes-cell("合作作品定义条：多人创作且贡献难分开。"),

  "s.120",
  source-statutes-dual-cell("120. 在香港以外地方等制作侵犯版权复制品(1)任何人如在香港以外地方制作任何输往香港而非供他私人和家居使用的物品，而他知道该物品假使在香港制作即会构成版权作品的侵犯版权复制品，该人即属犯罪。 (2)任何人如在香港以外地方制作经特定设计或改装以供制作属某版权作品的复制品的物品，而他知道或有理由相信该物品将会在香港用作或拟在香港用作制作该版权作品的侵犯版权复制品以供出售或出租，或以供为任何贸易或业务的目的或在任何贸易或业务的过程中使用，该人即属犯罪。 (由 2000年第64号第9条修订；由 2007年第15号第34条修订) (2A)就第(2)款而言，有关的贸易或业务是否包含经营版权作品的侵犯版权复制品并不具关键性。 (由 2000年第64号第9条增补) (3)任何人如在香港以外地方制作或从香港输出经特定设计或改装以供制作属某版权作品的复制品的物品，而他知道或有理由相信——(a)该物品将会或拟在香港以外地方用作制作输往香港的另一物品；及(b) (a)段提及的另一物品假使在香港制作，即会构成该版权作品的侵犯版权复制品， 该人即属犯罪。 (4)任何人如在香港或其他地方协助、教唆、怂使或促致另一人犯第(1)、(2)或(3)款所订罪行，即属以主犯身分犯该罪。 (5)第(1)、(2)及(3)款所订罪行并不损害第118条所订罪行。 (6)任何人犯第(1)、(2)或(3)款所订罪行，一经定罪，可处罚款$500,000及监禁8年。 (7)就本条而言， 物品(article)不包括过境物品。 (8)第115至117条(就与版权有关连的各种事宜而作出的推定)不适用于就本条所订罪行而进行的法律程序。", "120. Making infringing copies outside Hong Kong, etc. (1) A person commits an offence if he makes outside Hong Kong, for export to Hong Kong otherwise than for his private and domestic use, any article that he knows would, if it were made in Hong Kong, constitute an infringing copy of a copyright work. (2) A person commits an offence if he makes outside Hong Kong an article specifically designed or adapted for making copies of a particular copyright work knowing or having reason to believe that it is to be used or is intended to be used in Hong Kong for making an infringing copy of the copyright work for sale or hire or for use for the purpose of or in the course of any trade or business. (Amended 64 of 2000 s. 9 ; 15 of 2007 s. 34) (2A) It is immaterial for the purpose of subsection (2) whether or not the trade or business consists of dealing in infringing copies of copyright works. (Added 64 of 2000 s. 9) (3) A person commits an offence if he makes outside Hong Kong or exports from Hong Kong an article specifically designed or adapted for making copies of a particular copyright work, knowing or having reason to believe that— (a) the article is to be used or is intended to be used outside Hong Kong for making another article for export to Hong Kong; and (b) the latter article mentioned in paragraph (a) would, if it were made in Hong Kong, constitute an infringing copy of th..."),
  source-statutes-cell("在境外做、再输港的侵权复制品，照样可能触发本地刑责。"),

  "s.13",
  source-statutes-dual-cell("13. 版权的第一拥有权除第14 、 15 及 16条另有规定外，作品的作者是该作品的任何版权的第一拥有人。 [比照 1988 c. 48 s. 11(1) U.K.]", "13. First ownership of copyright The author of a work is the first owner of any copyright in it, subject to sections 14 , 15 and 16 . [cf. 1988 c. 48 s. 11(1) U.K.]"),
  source-statutes-cell("默认规则：作品一做出来，版权先归作者。"),

  "s.14",
  source-statutes-dual-cell("14. 雇员的作品(1)凡文学作品、戏剧作品、音乐作品、艺术作品或影片是由雇员在受雇工作期间制作的， 则——(a)除任何协议有相反的规定外；及(b)在符合第(2)款的规定下， 该雇员的雇主是该作品的版权的第一拥有人。 (2)除任何协议有相反的规定外，如有关雇主利用该等作品或在其允许下由他人利用该等作品，而利用的方式在该等作品创作当时是该雇主及有关雇员均不能合理地预料的，则雇主须就该项利用支付一笔偿金予该雇员，款额由该雇主及该雇员议定，如没有协议则由版权审裁处裁定。 [比照 1988 c. 48 s. 11(2) U.K.]", "14. Employee works (1) Where a literary, dramatic, musical or artistic work, or a film, is made by an employee in the course of his employment, his employer is the first owner of any copyright in the work subject to— (a) any agreement to the contrary; and (b) subsection (2). (2) Subject to any agreement to the contrary, where such work is exploited by his employer or by someone else with the employer’s permission in a way that could not reasonably have been contemplated by the employer and the employee at the time of making the work, the employer shall pay an award to the employee in respect of such exploitation at such amount as agreed between the employer and the employee or failing an agreement, as determined by the Copyright Tribunal. [cf. 1988 c. 48 s. 11(2) U.K.]"),
  source-statutes-cell("雇员在工作中做的作品，通常版权归雇主；特殊利用可能要另付补偿。"),

  "s.15",
  source-statutes-dual-cell("15. 委讬作品(1)凡作品是某人委讬制作的，而作者与委讬人之间订有就版权的享有权作出明确的规定的协议，则委讬作品的版权属于根据该协议享有版权的人。 (2)尽管有第(1)款及第13 及 103条的规定，委讬制作作品的人——(a)具有专用特许，可为作者及该委讬制作作品的人在委讬制作作品时可合理地预料的目的，利用该委讬作品；及(b)有权制止为任何他可合理地提出反对的目的而利用委讬作品。", "15. Commissioned works (1) Where a work is made on the commission of a person and there is an agreement between the author and the commissioner of the work which expressly provides for the entitlement to the copyright, copyright in the commissioned work belongs to the person who is entitled to the copyright under the agreement. (2) Notwithstanding subsection (1) and sections 13 and 103 , the person who commissioned the work— (a) has an exclusive licence to exploit the commissioned work for all purposes that could reasonably have been contemplated by the author and the person who commissioned the work at the time the work was commissioned; and (b) has the power to restrain any exploitation of the commissioned work for any purpose against which he could reasonably take objection."),
  source-statutes-cell("委托创作先看合同。合同没写清时，委托方仍有一定使用权。"),

  "s.194",
  source-statutes-dual-cell("194. 对版权拥有人的提述的解释(1)凡不同的人就一项作品不同方面的版权具有权利(不论是由于局部转让或其他原因)，则就本部某目的而言的版权拥有人即为有权享有与该目的有关的方面的版权的人。 (2)凡版权(或版权的任何方面)是由多于一人共同拥有的，则在本部中凡提述版权拥有人，即提述所有该等拥有人；故此特别是在须要取得版权拥有人特许的情况下，须要取得所有该等拥有人的特许。 [比照 1988 c. 48 s. 173 U.K.]", "194. Construction of references to copyright owner (1) Where different persons are (whether in consequence of a partial assignment or otherwise) entitled to different aspects of copyright in a work, the copyright owner for any purpose of this Part is the person who is entitled to the aspect of copyright relevant for that purpose. (2) Where copyright (or any aspect of copyright) is owned by more than one person jointly, references in this Part to the copyright owner are to all the owners, so that, in particular, any requirement of the licence of the copyright owner requires the licence of all of them. [cf. 1988 c. 48 s. 173 U.K.]"),
  source-statutes-cell("多人分持权利时，谁是“版权人”要按具体权利面向来拆分看。"),

  "s.2",
  source-statutes-dual-cell("2. 版权及版权作品(1)版权是按照本部而存在于下列类别的作品的产权——(a)原创的文学作品、戏剧作品、音乐作品或艺术作品； (b)声音纪录、影片、广播或有线传播节目；及(c)已发表版本的排印编排。 (2)在本部中， 版权作品(copyright work)指有版权存在的该等类别作品中的任何作品。 (3)除非已符合本部中关于享有版权保护所须具备的资格的规定(参阅第177条及该条所提述的条文)，否则版权并不存在于任何作品。 (由 2022年第16号第3条修订) [比照 1988 c. 48 s. 1 U.K.]", "2. Copyright and copyright works (1) Copyright is a property right which subsists in accordance with this Part in the following descriptions of work— (a) original literary, dramatic, musical or artistic works; (b) sound recordings, films, broadcasts or cable programmes; and (c) the typographical arrangement of published editions. (2) In this Part copyright work (版权作品) means a work of any of those descriptions in which copyright subsists. (3) Copyright does not subsist in a work unless the requirements of this Part with respect to qualification for copyright protection are met (see section 177 and the provisions referred to there). [cf. 1988 c. 48 s. 1 U.K.]"),
  source-statutes-cell("先定版权对象：文学、戏剧、音乐、艺术及录音录像等。"),

  "s.23",
  source-statutes-dual-cell("23. 因复制而侵犯版权(1)复制有关作品是受任何类别的版权作品的版权所限制的作为；在本部中，凡提述复制及复制品，均按以下条文解释。 (2)复制任何作品指以任何实质形式复制该作品，并包括藉电子方法将作品贮存于任何媒体。 (3)就艺术作品而言，复制包括将平面作品制成立体的复制品以及将立体作品制成平面的复制品。 (4)就影片、电视广播或有线传播节目而言，复制包括制作构成该影片、广播或有线传播节目的全部或任何实质部分的任何影像的照片。 (5)就已发表版本的排印编排而言，复制指制作该编排的精确复制品。 (6)就任何类别的作品而言，复制包括制作该等作品的短暂存在的复制品或为该等作品的其他用途而附带制作复制品。 [比照 1988 c. 48 s. 17 U.K.]", "23. Infringement of copyright by copying (1) The copying of the work is an act restricted by the copyright in every description of copyright work; and references in this Part to copying and copies are construed as follows. (2) Copying of a work means reproducing the work in any material form. This includes storing the work in any medium by electronic means. (3) In relation to an artistic work copying includes the making of a copy in 3 dimensions of a 2-dimensional work and the making of a copy in 2 dimensions of a 3-dimensional work. (4) Copying in relation to a film, television broadcast or cable programme includes making a photograph of the whole or any substantial part of any image forming part of the film, broadcast or cable programme. (5) Copying in relation to the typographical arrangement of a published edition means making a facsimile copy of the arrangement. (6) Copying in relation to any description of work includes the making of copies which are transient or are incidental to some other use of the work. [cf. 1988 c. 48 s. 17 U.K.]"),
  source-statutes-cell("复制不只指影印，也包括电子存储和临时副本。"),

  "s.24",
  source-statutes-dual-cell("24. 以向公众发放复制品方式侵犯版权(1)向公众发放有关作品的复制品，是受任何类别的版权作品的版权所限制的作为。 (2)在本部中，凡提述向公众发放作品的复制品，即提述由版权拥有人或在其同意下将以前从未在香港或其他地方发行的复制品发行的作为。 (3)在本部中，凡提述向公众发放作品的复制品，并不包括——(a)以前曾发行的复制品的任何其后的分发、售卖、租赁或借出(但参阅第25条 ︰以租赁方式侵犯版权)；或(b)该等复制品其后输入香港。 (4)在本部中，凡提述发放作品的复制品，包括发放原本的作品及发放电子形式的复制品。 [比照 1988 c. 48 s. 18 U.K.]", "24. Infringement by issue of copies to the public (1) The issue of copies of the work to the public is an act restricted by the copyright in every description of copyright work. (2) References in this Part to the issue of copies of a work to the public are to the act of putting into circulation copies not previously put into circulation, in Hong Kong or elsewhere, by or with the consent of the copyright owner. (3) References in this Part to the issue of copies of a work to the public do not include— (a) any subsequent distribution, sale, hiring or loan of copies previously put into circulation (but see section 25 : infringement by rental); or (b) any subsequent importation of those copies into Hong Kong. (4) References in this Part to the issue of copies of a work include the issue of the original and the issue of copies in electronic form. (Amended E.R. 2 of 2019) [cf. 1988 c. 48 s. 18 U.K.]"),
  source-statutes-cell("首次向公众发放复制品会触发版权控制，后续流转规则另看条文。"),

  "s.25",
  source-statutes-dual-cell("25. 以租赁作品予公众方式侵犯版权(1)租赁任何以下作品的复制品予公众，是受该作品的版权所限制的作为——(a)电脑程式； (b)声音纪录； (c)影片； (d)收录在声音纪录内的文学作品、戏剧作品或音乐作品。 (由 2007年第15号第6条代替。由 2022年第16号第11条修订) (2)在本部中，除本条以下条文另有规定外， 租赁(rental)指为直接或间接的经济或商业利益，而令作品的复制品在该复制品将予或可予归还的条款下供人使用。 (3)租赁(rental)一词不包括——(a)提供作公开表演、播放或放映之用，或作向公众传播之用； (由 2022年第16号第11条修订) (b)提供作公开陈列之用；或(由 2007年第15号第6条修订) (c)提供作即场参考之用。 (4)在本部中，凡提述租赁作品的复制品，包括租赁原本的作品。 [比照 1988 c .48 s. 18A U.K.]", "25. Infringement by rental of work to the public (1) The rental of copies of any of the following works to the public is an act restricted by the copyright in the work— (a) a computer program; (b) a sound recording; (c) a film; (d) a literary, dramatic or musical work included in a sound recording. (Replaced 15 of 2007 s. 6 . Amended 16 of 2022 s. 11) (2) In this Part, subject to the following provisions of this section, rental (租赁) means making a copy of the work available for use, on terms that it will or may be returned, for direct or indirect economic or commercial advantage. (3) The expression rental (租赁) does not include— (a) making available for the purpose of public performance, playing or showing in public or communicating to the public; (Amended 16 of 2022 s. 11) (b) making available for the purpose of exhibition in public; or (c) making available for on-the-spot reference use. (4) References in this Part to the rental of copies of a work include the rental of the original. [cf. 1988 c. 48 s. 18A U.K.]"),
  source-statutes-cell("把作品复制品拿去租，很多情况下也算受版权控制的行为。"),

  "s.30",
  source-statutes-dual-cell("30. 间接侵犯版权︰输入或输出侵犯版权复制品任何人未获作品的版权拥有人的特许，将该作品的复制品输入或输出香港，而他知道或有理由相信该复制是该作品的侵犯版权复制品，而且他输入或输出该复制品并非供自己私人和家居使用，即属侵犯该作品的版权。 [比照 1988 c. 48 s. 22 U.K.]", "30. Secondary infringement: importing or exporting infringing copy The copyright in a work is infringed by a person who, without the licence of the copyright owner, imports into Hong Kong or exports from Hong Kong, otherwise than for his private and domestic use, a copy of the work which is, and which he knows or has reason to believe to be, an infringing copy of the work. [cf. 1988 c. 48 s. 22 U.K.]"),
  source-statutes-cell("明知是侵权复制品还进出口（非私人家用），会构成侵权。"),

  "s.31",
  source-statutes-dual-cell("31. 间接侵犯版权︰进行侵犯版权复制品交易(由 2022年第16号第16条修订) (1)任何人未获作品的版权拥有人的特许，就该作品的复制品作出以下作为，而他知道或有理由相信该复制品是该作品的侵犯版权复制品，即属侵犯该作品的版权——(由 2000年第64号第2条修订) (a)为任何贸易或业务的目的或在任何贸易或业务的过程中，管有该复制品； (由 2000年第64号第2条代替。由 2007年第15号第7条修订) (b)将该复制品出售、出租、要约出售或要约出租，或为出售或出租而展示该复制品； (c)为任何贸易或业务的目的或在任何贸易或业务的过程中，公开陈列或分发该复制品；或(由 2000年第64号第2条代替。由 2007年第15号第7条修订) (d)并非为任何贸易或业务的目的，亦并非在任何贸易或业务的过程中，分发该复制品并达到损害版权拥有人的程度。 (由 2000年第64号第2条修订；由 2007年第15号第7条修订) (2)就第(1)(a)及(c)款而言，有关的贸易或业务是否包含经营版权作品的侵犯版权复制品并不具关键性。 (由 2000年第64号第2条增补) (3)就第(1)(d)款而言，法院在裁定某作品的侵犯版权复制品的分发有否达到损害版权拥有人的权利的程度时，可考虑有关个案的整体情况，并尤其可考虑——(a)该项分发的目的； (b)该作品的性质，包括其商业价值(如有的话)； (c)相对于该作品的整体，被分发的遭复制部分所占的数量及实质分量； (d)该项分发的方式；及(e)因应该项分发而对版权拥有人所造成的经济损害(如有的话)，包括该项分发对该作品的潜在市场或价值的影响。 (由 2022年第16号第16条增补) [比照 1988 c. 48 s. 23 U.K.]", "31. Secondary infringement: dealing with infringing copy (Amended 16 of 2022 s. 16) (1) The copyright in a work is infringed by a person who, without the licence of the copyright owner— (Amended 64 of 2000 s. 2) (a) possesses for the purpose of or in the course of any trade or business; (Replaced 64 of 2000 s. 2 . Amended 15 of 2007 s. 7) (b) sells or lets for hire, or offers or exposes for sale or hire; (c) exhibits in public or distributes for the purpose of or in the course of any trade or business; or (Replaced 64 of 2000 s. 2 . Amended 15 of 2007 s. 7) (d) distributes (otherwise than for the purpose of or in the course of any trade or business) to such an extent as to affect prejudicially the owner of the copyright, (Amended 64 of 2000 s. 2 ; 15 of 2007 s. 7) a copy of a work which is, and which he knows or has reason to believe to be, an infringing copy of the work. (2) It is immaterial for the purpose of subsection (1)(a) and (c) whether or not the trade or business consists of dealing in infringing copies of copyright works. (Added 64 of 2000 s. 2) (3) For the purposes of subsection (1)(d) , in determining whether any distribution of an infringing copy of a work is made to such an extent as to affect prejudicially the owner of the copyright, the court may take into account all the circumstances of the case and, in particular— (a) the purpose of the distribution; (b) ..."),
  source-statutes-cell("明知是侵权复制品还卖、租、展示、分发，通常都会踩线。"),

  "s.36",
  source-statutes-dual-cell("36. 就第30 及 31条而言的免责辩护(1)现声明如有某作品的复制品是在制作它的所在国家、地区或地方合法地制作的，且它仅凭借第35(3)条而属侵犯版权复制品，则就第30 及 31条而言以及为免生疑问，在根据第30 或 31条而就某作品的复制品进行的侵犯版权诉讼中，如被告人证明——(由 2007年第15号第11条修订) (a)他已作出合理查究足以使他自己信纳该已输入或拟输入香港的该作品的复制品并非该作品的侵犯版权复制品； (b)他基于合理理由而信纳在有关个案的情况下，该复制品并非侵犯版权复制品；及(c)没有其他本会致使他合理地怀疑该复制品是侵犯版权复制品的情况， 则他已证明他没有理由相信该复制品是侵犯版权复制品。 (2)法院在裁定被告人是否已根据第(1)款证明他没有理由相信该复制品是侵犯版权复制品时，可顾及的因素包括(但不限于)以下事项——(a)他是否已就有关类别作品向有关的行业团体作出查究； (b)他是否已给予通知促请有关的版权拥有人或专用特许持有人注意他在输入和出售该作品的复制品方面的权益； (c)他是否已遵从就有关类别作品的供应而可能存在的实务守则； (d)对被告作出的该等查究的回应(如有的话)是否合理和及时； (e)他是否已获提供有关的版权拥有人或专用特许持有人(视属何情况而定)的姓名或名称、地址及其联络之详细资料； (f)他是否已获提供有关作品首日发表之日期； (g)他是否已获提供任何有关专用特许之证明。 (3)凡某人一如第30 或 31条所述般侵犯版权，在针对该人侵犯版权的诉讼中，如该人证明以下事项，即可以此作为免责辩护——(a)他已向版权拥有人或专用特许持有人(视属何情况而定)订购该作品的复制品，以获得该作品的复制品的供应； (b)他已向某人作出订购，但该人基于不合理理由而不作出提供或在不合理的条款下始同意提供，故此其作为并不合情理；及(c)有关输入是在版权拥有人或专用特许特有人作出该不合情理的作为之后并且是在第35(4)(b)条指明的期间届满之后进行的。 (4)法院在裁定版权拥有人或专用特许持有人是否已作出不合情理的作为时，须将个别行业为有秩序地分发该类别作品的复制品而既有的惯常做法列为考虑因素，尤其须考虑该订单如获履行，会否与版权拥有人或专用特许持有人对该作品的正常利用有所抵触，或会否不合理地损害版权拥有人或专用特许持有人的合法权益。 (5)法院在裁定是否基于不合理理由而不作出提供或在不合理的条款下始同意提供时，须考虑个别行业或个别公众的合理需求，包括但不限于价格及提货时间、该行业对在香港存货之处理、该行业对个别媒体、类别或语言的产品之一般处理、订单之大小、已作之查询以及有无任何人士以前曾经向个别供应商订货而未得到兑现。", "36. Defences for the purposes of sections 30 and 31 (1) For the purposes of sections 30 and 31 and for the avoidance of doubt, it is declared that if in an action for infringement of copyright under section 30 or 31 in respect of a copy of a work which is an infringing copy by virtue only of section 35(3) and which was lawfully made in the country, territory or area where it was made, the defendant proves that— (Amended 15 of 2007 s. 11) (a) he had made reasonable enquiries sufficient to satisfy himself that the copy of the work imported or proposed to be imported into Hong Kong was not an infringing copy of the work; (b) he had reasonable grounds to be satisfied in the circumstances of the case that the copy was not an infringing copy; and (c) there were no other circumstances which would have led him reasonably to suspect that the copy was an infringing copy, he has proved that he did not have reason to believe that the copy was an infringing copy. (2) In determining whether a defendant has proved under subsection (1) that he did not have reason to believe that the copy was an infringing copy of the work, the court may have regard to, including but not limited to, the following— (a) whether he had made enquiries with a relevant trade body in respect of that category of work; (b) whether he had given any notice drawing attention of the copyright owner or exclusive licensee ..."),
  source-statutes-cell("研究/私人学习可在条件内使用，不能无限扩大。"),

  "s.37",
  source-statutes-dual-cell("37. 引言条文(1)本分部的条文指明某些在尽管有版权存在的情况下仍可就版权作品而作出的作为；该等条文只关乎侵犯版权的问题而不影响限制作出任何该等指明作为的任何其他权利或义务。 (2)凡本分部规定某项作为不属侵犯版权，或可作出该作为而不侵犯版权，而没有特别提及某类别的版权作品，则有关作为并不属侵犯任何类别的作品的版权。 (3)在决定本分部指明的作为是否可在尽管有版权存在的情况下就版权作品而作出时，基本考虑因素是该项作为并不与版权拥有人对作品的正常利用有所抵触，以及该项作为并没有不合理地损害版权拥有人的合法权益。 (4)不得从凭借本分部可予作出而不属侵犯版权的任何作为的描述，而推论受任何类别作品的版权所限制的作为的范围。 (5)本分部各条条文的解释互相独立，故某作为并不属于某条文的范围，并不表示另一条文不涵盖该作为。 [比照 1988 c. 48 s. 28 U.K.]", "37. Introductory provisions (1) The provisions of this Division specify acts which may be done in relation to copyright works notwithstanding the subsistence of copyright; they relate only to the question of infringement of copyright and do not affect any other right or obligation restricting the doing of any of the specified acts. (2) Where it is provided by this Division that an act does not infringe copyright, or may be done without infringing copyright, and no particular description of copyright work is mentioned, the act in question does not infringe the copyright in a work of any description. (3) In determining whether an act specified in this Division may be done in relation to a copyright work notwithstanding the subsistence of copyright, the primary consideration is that the act does not conflict with a normal exploitation of the work by the copyright owner and does not unreasonably prejudice the legitimate interests of the copyright owner. (4) No inference is to be drawn from the description of any act which may by virtue of this Division be done without infringing copyright as to the scope of the acts restricted by the copyright in any description of work. (5) The provisions of this Division are to be construed independently of each other, so that the fact that an act does not fall within one provision does not mean that it is not covered by another provision. [cf..."),
  source-statutes-cell("教学场景可有例外，但要守范围。"),

  "s.39",
  source-statutes-dual-cell("39. 批评、评论、引用及报道和评论时事(1)为批评或评论某作品(有关作品)或另一作品，或为批评或评论某作品的表演，而公平处理有关作品，只要符合以下条件，即不属侵犯有关作品的任何版权，而就有关作品的已发表版本而言，亦不属侵犯其排印编排的版权——(a)有关作品已向公众发行或传播；及(b)该项处理附有足够的确认声明(第(6)款另有规定者除外)。 (2)不论为批评、评论或其他目的而引用某作品，只要符合以下条件，即不属侵犯该作品的版权——(a)该作品已向公众发行或传播； (b)该项引用，属公平处理该作品； (c)该作品是为某特定目的而引用，而引用的程度，不超逾该目的所需的程度；及(d)该项引用附有足够的确认声明(第(6)款另有规定者除外)。 (3)为报道或评论时事而公平处理某作品，只要附有足够的确认声明(第(6)款另有规定者除外)，即不属侵犯该作品的任何版权，而就有关作品的已发表版本而言，亦不属侵犯其排印编排的版权。 (4)法院在裁定处理作品是否第(1)、 (2)(b)或(3)款所指的公平处理时，须考虑有关个案的整体情况，并尤其须考虑——(a)该项处理的目的及性质，包括该项处理是否为非牟利的目的而作出，以及是否属商业性质； (b)该作品的性质； (c)相对于该作品的整体，被处理的部分所占的数量及实质分量；及(d)该项处理对该作品的潜在市场或价值的影响。 (5)就第(1)(a)及(2)(a)款而言——(a)如某作品已经以任何方式(向公众传播除外)，供给公众，则该作品即属已向公众发行，供给的方式包括——(i)向公众发放该作品的复制品； (ii)将该作品的复制品，租赁予公众；及(iii)公开表演、陈列、播放或放映该作品；及(b)在断定某作品是否已向公众发行或传播时，不得考虑任何未经授权的作为。 (6)就第(1)(b) 、 (2)(d)及(3)款而言，如将足够的确认声明附于有关的处理，并非合理地切实可行，则该项处理不须附有该声明。 (由 2022年第16号第19条代替)", "39. Criticism, review, quotation, and reporting and commenting on current events (1) Fair dealing with a work (the work) for the purpose of criticism or review of the work or another work, or of a performance of a work, does not infringe any copyright in the work or, for a published edition of the work, in the typographical arrangement of the published edition, if— (a) the work has been released or communicated to the public; and (b) (subject to subsection (6)) the dealing is accompanied by a sufficient acknowledgement. (2) Copyright in a work is not infringed by the use of a quotation from the work (whether for the purpose of criticism, review or otherwise) if— (a) the work has been released or communicated to the public; (b) the use of the quotation is fair dealing with the work; (c) the extent of the quotation is no more than is required by the specific purpose for which it is used; and (d) (subject to subsection (6)) the use of the quotation is accompanied by a sufficient acknowledgement. (3) Fair dealing with a work for the purpose of reporting or commenting on current events does not infringe any copyright in the work or, for a published edition of the work, in the typographical arrangement of the published edition, if (subject to subsection (6)) the dealing is accompanied by a sufficient acknowledgement. (4) In determining whether any dealing with a work is fair deali..."),
  source-statutes-cell("合理使用的主力条款：评论、时事报道、引用等，在满足条件时可作为抗辩。"),

  "s.4",
  source-statutes-dual-cell("4. 文学作品、戏剧作品及音乐作品(1)在本部中——文学作品(literary work)指除戏剧作品或音乐作品外的任何写出、讲出或唱出的作品，并据此包括——(a)资料或其他材料的任何形式的编汇，且因其内容的选取或编排而构成智力创作，并包括(但不限于)列表； (b)电脑程式；及(c)为电脑程式而备的预备设计材料； 音乐作品(musical work)指由音乐构成的作品，但不包括拟伴随该等音乐而唱出或讲出的文字或表演的动作； 戏剧作品(dramatic work)包括舞蹈作品或默剧作品。 (2)除非文学作品、戏剧作品或音乐作品以书面或其他方式记录，否则版权并不存在于该等作品，而在该等作品经如此记录之前，其版权亦不存在；在本部中，凡提述该等作品的制作时间，即提述该等作品经如此记录的时间。 (3)就第(2)款而言，作品是否由作者记录或是否经作者的允许而记录并不具关键性；如作品并非由作者记录，则第(2)款对版权是否在独立于经记录的作品的情况下存在于纪录本身此一问题，并无影响。 [比照 1988 c. 48 s. 3 U.K.]", "4. Literary, dramatic and musical works (1) In this Part— dramatic work (戏剧作品) includes a work of dance or mime; literary work (文学作品) means any work, other than a dramatic or musical work, which is written, spoken or sung, and accordingly includes— (a) a compilation of data or other material, in any form, which by reason of the selection or arrangement of its contents constitutes an intellectual creation, including but not limiting to a table; (b) a computer program; and (c) preparatory design material for a computer program; musical work (音乐作品) means a work consisting of music, exclusive of any words or action intended to be sung, spoken or performed with the music. (2) Copyright does not subsist in a literary, dramatic or musical work unless and until it is recorded, in writing or otherwise; and references in this Part to the time at which such a work is made are to the time at which it is so recorded. (3) It is immaterial for the purposes of subsection (2) whether the work is recorded by or with the permission of the author; and where it is not recorded by the author, nothing in that subsection affects the question whether copyright subsists in the record as distinct from the work recorded. [cf. 1988 c. 48 s. 3 U.K.]"),
  source-statutes-cell("文学作品范围很广，文字、表格、数据库都可能算。"),

  "s.42",
  source-statutes-dual-cell("42. 供教育用途的选集(1)凡从已发表的文学作品或戏剧作品中摘录短的片段而将其包括在集合本中，而该集合本——(a)是拟在教育机构中使用的，并且在集合本名称中及由集合本的发表人发放或代表集合本的发表人发放的宣传品中均如此描述；及(b)主要是由没有版权存在的材料构成的， 则只要该等作品本身并非拟在该教育机构中使用并且将该等作品包括在该集合本中是附有足够的确认声明的，将该片段包括在该集合本中并不属侵犯该作品的版权。 (2)第(1)款并不授权同一发表人在任何5年期间内，从由同一作者制作的版权作品中抽取多于2项摘录，以包括在该发表人所发表的集合本中。 (3)就作品的任何特定片段而言，第(2)款提述的从由同一作者制作的作品中抽取摘录——(a)须视作包括从由该作者与他人共同制作的作品中抽取摘录；及(b)如有关片段是从该等作品中抽取的，则须视作包括从由其中任何一位作者制作的作品(不论该作品为该作者单独制作或与另一作者共同制作)中抽取摘录。 (4)在本条中，凡提述在教育机构中使用作品，即提述为该等机构的教育目的而使用。 [比照 1988 c. 48 s. 33 U.K.]", "42. Anthologies for educational use (1) The inclusion of a short passage from a published literary or dramatic work in a collection which— (a) is intended for use in educational establishments and is so described in its title, and in any advertisements issued by or on behalf of the publisher; and (b) consists mainly of material in which no copyright subsists, does not infringe the copyright in the work if the work itself is not intended for use in such establishments and the inclusion is accompanied by a sufficient acknowledgement. (2) Subsection (1) does not authorize the inclusion of more than 2 excerpts from copyright works by the same author in collections published by the same publisher over any period of 5 years. (3) In relation to any given passage the reference in subsection (2) to excerpts from works by the same author— (a) is taken to include excerpts from works by him in collaboration with another; and (b) if the passage in question is from such a work, is taken to include excerpts from works by any of the authors, whether alone or in collaboration with another. (4) References in this section to the use of a work in an educational establishment are to any use for the educational purposes of such an establishment. [cf. 1988 c. 48 s. 33 U.K.]"),
  source-statutes-cell("课堂教学使用的边界补充条：能不能用、能用到哪里，主要看这里。"),

  "s.43",
  source-statutes-dual-cell("43. 在教育机构的活动过程中表演、播放或放映作品(1)凡——(a)在教育机构的活动过程中由教师或学生表演文学作品、戏剧作品或音乐作品；或(b)在教育机构中由任何人为教学的目的而表演文学作品、戏剧作品或音乐作品， 而观众或听众只包括或主要包括该机构的教师和学生、该机构的学生的父母或监护人及与该机构的活动有直接关连的其他人，则就侵犯版权而言，该表演不属公开表演。 (由 2007年第15号第15条修订) (2)为教学或接受教学的目的而在教育机构中向上述观众或听众播放或放映声音纪录、影片、广播或有线传播节目，就侵犯版权而言，不属公开播放或放映有关作品。 (由 2007年第15号第15条修订) (3) (由 2007年第15号第15条废除) [比照 1988 c. 48 s. 34 U.K.]", "43. Performing, playing or showing work in course of activities of educational establishments (1) The performance of a literary, dramatic or musical work before an audience consisting wholly or mainly of teachers and pupils at an educational establishment, parents or guardians of pupils at the establishment, and other persons directly connected with the activities of the establishment— (Amended 15 of 2007 s. 15) (a) by a teacher or pupil in the course of the activities of the establishment; or (b) at the establishment by any person for the purposes of instruction, is not a public performance for the purposes of infringement of copyright. (2) The playing or showing of a sound recording, film, broadcast or cable programme before such audience at an educational establishment for the purposes of giving or receiving instruction is not a playing or showing of the work in public for the purposes of infringement of copyright. (Amended 15 of 2007 s. 15) (3) (Repealed 15 of 2007 s. 15) [cf. 1988 c. 48 s. 34 U.K.]"),
  source-statutes-cell("课堂公开表演/展示在特定条件下可豁免。"),

  "s.44",
  source-statutes-dual-cell("44. 由教育机构制作纪录或复制品或作出传播：广播或有线传播节目(由 2022年第16号第30条修订) (1)任何广播或有线传播节目的纪录或该纪录的复制品，在以下情况之下，可由教育机构或代教育机构为该机构的教育目的而制作，而不属侵犯该广播或有线传播节目或包括在其中的任何作品的版权——(a)该机构制作的该纪录已包含确认作者的声明或确认被记录的作品所载的其他创作努力的声明；及(b)并非为图利而制作。 (1A)获某教育机构授权的人，可向获授权收讯人传播按照第(1)款制作的广播或有线传播节目的纪录，或该纪录的复制品，该项传播只要符合以下规定，便不属侵犯版权——(a)该人是为了该机构的教育目的，而作出该项传播；及(b)该机构采取一切合理步骤，以确保——(i)只有获授权收讯人接收该项传播；及(ii)该等获授权收讯人不会制作该项传播的复制品，亦不会将该项传播作进一步传送。 (由 2022年第16号第30条增补) (2)如有特许计划下的特许，授权进行有关记录或复制，或授权作出有关传播，而制作有关纪录或复制品的人或作出该项传播的人，已知道或应已知道该事实，则本条并不授权进行(或在该特许所授权的范围内进行)该项记录或复制，或向获授权收讯人作出(或在该特许所授权的范围内作出)该项传播。 (由 2022年第16号第30条代替) (3)凡任何纪录或复制品(假若非因本条该复制品即属侵犯版权复制品)按照本条制作，但其后该复制品用作交易，则就该项交易而言，该复制品须视为侵犯版权复制品，又如该项交易侵犯版权，则就所有其后的目的而言，该复制品须视为侵犯版权复制品。 (由 2022年第16号第30条修订) (4)就第(3)款而言， 如——(a)在并非为有关教育机构的教育目的之情况下，为任何贸易或业务的目的，或在任何贸易或业务的过程中，管有、公开陈列或分发某纪录或复制品； (b)出售或出租某纪录或复制品、要约出售或要约出租某纪录或复制品，或为出售或出租而展示某纪录或复制品；或(c)向公众传播某纪录或复制品(该项传播根据第(1A)款不属侵犯版权的情况除外)， 该纪录或复制品即属用作交易。 (由 2022年第16号第30条增补) (5)在本条中——获授权收讯人(authorized recipient)就获某教育机构授权的人作出的传播而言，指已获该机构授权(或已获该机构的代表授权)接收该项传播的该机构的教师或学生。 (由 2022年第16号第30条增补) [比照 1988 c. 48 s. 35 U.K.]", "44. Recording, copying or communication by educational establishments: broadcasts or cable programmes (Amended 16 of 2022 s. 30) (1) A recording of a broadcast or cable programme, or a copy of such a recording may be made by or on behalf of an educational establishment for the educational purposes of that establishment without thereby infringing the copyright in the broadcast or cable programme, or in any work included in it, if— (a) an acknowledgement of authorship or other creative effort contained in the work recorded is incorporated in the recording made by the establishment; and (b) it is not made for gain. (1A) A person authorized by an educational establishment may, without infringing copyright, communicate to an authorized recipient a recording, or a copy of a recording, of a broadcast or cable programme that has been made in accordance with subsection (1) if— (a) the person makes the communication for the educational purposes of the establishment; and (b) the establishment takes all reasonable steps to ensure that— (i) only authorized recipients receive the communication; and (ii) the authorized recipients do not make any copy or further transmission of the communication. (Added 16 of 2022 s. 30) (2) Recording, copying or communicating to authorized recipients is not authorized by this section if, or to the extent that, licences under licensing schemes are available..."),
  source-statutes-cell("为教学而复制有比例和用途限制。"),

  "s.45",
  source-statutes-dual-cell("45. 由教育机构或学生制作复制品或作出传播：已发表作品中的片段或摘录(由 2007年第15号16条修订；由 2022年第16号第31条修订) (1)教育机构或其代表可为教学目的，而学生亦可为在任何由教育机构提供的指明课程中接受教学的目的，在合理的范围内制作艺术作品或已发表的文学作品、戏剧作品或音乐作品的片段或已发表的声音纪录或影片的摘录的复制品，而不属侵犯该等作品的版权、排印编排的版权，或该声音纪录或影片的版权(视属何情况而定)。 (由 2007年第15号16条修订；由 2022年第16号第31条修订) (1A)获某教育机构授权的人，可向获授权收讯人传播按照第(1)款制作的艺术作品、已发表的文学作品、戏剧作品或音乐作品的片段或已发表的声音纪录或影片的摘录的复制品，该项传播只要符合以下规定，便不属侵犯版权——(a)该人是为了该机构的教育目的，而作出该项传播；及(b)该机构采取一切合理步骤，以确保——(i)只有获授权收讯人接收该项传播；及(ii)该等获授权收讯人不会制作该项传播的复制品，亦不会将该项传播作进一步传送。 (由 2022年第16号第31条增补) (2)如有特许计划下的特许，授权进行有关复制，或授权作出有关传播，而制作有关复制品的人或作出该项传播的人，已知道或应已知道该事实，则本条并不授权进行(或在该特许所授权的范围内进行)该项复制，或向获授权收讯人作出(或在该特许所授权的范围内作出)该项传播。 (由 2022年第16号第31条代替) (3)凡任何复制品(假使非因本条该复制品即属侵犯版权复制品)按照本条制作，但其后该复制品用作交易，则就该项交易而言，该复制品须视为侵犯版权复制品，又如该项交易侵犯版权，则就所有其后的目的而言，该复制品须视为侵犯版权复制品。 (由 2022年第16号第31条修订) (4)就第(3)款而言， 如——(a)在并非为有关教育机构的教育目的之情况下，为任何贸易或业务的目的，或在任何贸易或业务的过程中，管有、公开陈列或分发某复制品； (b)出售或出租某复制品、要约出售或要约出租某复制品，或为出售或出租而展示某复制品；或(c)向公众传播某复制品(该项传播根据第(1A)款不属侵犯版权的情况除外)， 该复制品即属用作交易。 (由 2022年第16号第31条增补) (5)在本条中——获授权收讯人(authorized recipient)就获某教育机构授权的人作出的传播而言，指已获该机构授权(或已获该机构的代表授权)接收该项传播的该机构的教师或学生。 (由 2022年第16号第31条增补) [比照 1988 c. 48 s. 36 U.K.]", "45. Copying or communication by educational establishments or pupils: passages or extracts from published works (Amended 15 of 2007 s. 16 ; 16 of 2022 s. 31) (1) Copies of artistic works or of passages from published literary, dramatic or musical works, or extracts from published sound recordings or films, may, to a reasonable extent, be made by or on behalf of an educational establishment for the purposes of giving instruction, or by a pupil for the purposes of receiving instruction in a specified course of study provided by an educational establishment, without infringing any copyright in the work, in the typographical arrangement, or in the sound recording or film (as the case may be). (Amended 15 of 2007 s. 16 ; 16 of 2022 s. 31) (1A) A person authorized by an educational establishment may, without infringing copyright, communicate to an authorized recipient a copy of an artistic work, a passage from a published literary, dramatic or musical work, or an extract from a published sound recording or film, that has been made in accordance with subsection (1) if— (a) the person makes the communication for the educational purposes of the establishment; and (b) the establishment takes all reasonable steps to ensure that— (i) only authorized recipients receive the communication; and (ii) the authorized recipients do not make any copy or further transmission of the communication...."),
  source-statutes-cell("教育广播与录制的合规边界。"),

  "s.54",
  source-statutes-dual-cell("54. 司法程序(由 2007年第15号第18条修订) (1)为司法程序的目的而作出任何事情，并不属侵犯版权。 (2)为报道司法程序的目的而作出任何事情，并不属侵犯版权；但这不得解释为授权任何人复制本身是该等程序的已发表报道的作品。 (由 2022年第16号第111条修订) (由 1999年第22号第3条修订；由 2007年第15号第18条修订) [比照 1988 c. 48 s. 45 U.K.]", "54. Judicial proceedings (Amended 15 of 2007 s. 18) (1) Copyright is not infringed by anything done for the purposes of judicial proceedings. (Amended 15 of 2007 s. 18) (2) Copyright is not infringed by anything done for the purposes of reporting such proceedings; but this is not to be construed as authorizing the copying of a work which is itself a published report of the proceedings. [cf. 1988 c. 48 s. 45 U.K.]"),
  source-statutes-cell("司法程序相关使用通常有较强豁免。"),

  "s.54B",
  source-statutes-dual-cell("54B. 立法会(1)以下作为不属侵犯版权——(a)为立法会程序的目的而作出任何事情；或(b)为行使立法会的权力及执行其职能的目的而——(i)由立法会议员或任何人代立法会议员；或(ii)由立法会行政管理委员会或任何人代立法会行政管理委员会， 作出任何事情。 (2)为报道立法会程序的目的而作出任何事情，并不属侵犯版权；但这不得解释为授权任何人复制本身是该等程序的已发表报道的作品。 (由 2022年第16号第111条修订) (由 2007年第15号第17条增补)", "54B. Legislative Council (1) Copyright is not infringed by— (a) anything done for the purposes of the proceedings of the Legislative Council; or (b) anything done by or on behalf of— (i) the members of the Legislative Council; or (ii) The Legislative Council Commission, for the purposes of the exercise and discharge by the Legislative Council of its powers and functions. (2) Copyright is not infringed by anything done for the purposes of reporting the proceedings of the Legislative Council; but this is not to be construed as authorizing the copying of a work which is itself a published report of the proceedings. (Added 15 of 2007 s. 17)"),
  source-statutes-cell("立法会程序相关用途的例外条款。"),

  "s.55",
  source-statutes-dual-cell("55. 法定研讯(1)为法定研讯的程序的目的而作出任何事情，并不属侵犯版权。 (2)为报道公开进行的该等程序的目的而作出任何事情，并不属侵犯版权；但这不得解释为授权任何人复制本身是该等程序的已发表报道的作品。 (由 2022年第16号第111条修订) (3)向公众传播法定研讯的报告书(载有某作品或其材料者)，或向公众发放该报告书的文本，并不属侵犯该作品的版权。 (由 2022年第16号第43条修订) (4)在本条中——法定研讯(statutory inquiry)指——(a)依据《调查委员会条例》(第86章)进行的研讯或调查；或(b)由条例或根据条例所施加的责任或由条例或根据条例所赋予的权力，而进行的研讯或调查。 [比照 1988 c. 48 s. 46 U.K.]", "55. Statutory inquiries (1) Copyright is not infringed by anything done for the purposes of the proceedings of a statutory inquiry. (2) Copyright is not infringed by anything done for the purposes of reporting any such proceedings held in public; but this is not to be construed as authorizing the copying of a work which is itself a published report of the proceedings. (3) Copyright in a work is not infringed by communicating to the public the report of a statutory inquiry containing the work or material from it or by issuing copies of the report to the public. (Amended 16 of 2022 s. 43) (4) In this section— statutory inquiry (法定研讯) means an inquiry held or investigation conducted in pursuance of— (a) the Commissions of Inquiry Ordinance (Cap. 86); or (b) a duty imposed or power conferred by or under an Ordinance. [cf. 1988 c. 48 s. 46 U.K.]"),
  source-statutes-cell("法定研讯场景下的豁免条款。"),

  "s.56",
  source-statutes-dual-cell("56. 开放予公众查阅或在公事登记册内的材料(1)依据法例规定须开放予公众查阅的材料，或法定登记册内的材料，如由适当的人或在其授权下复制，并且只复制该材料中属于任何类别的事实资料，而复制的目的并不涉及向公众传播该等材料或向公众发放该等材料的复制品，则该项复制并不属侵犯版权。 (由 2022年第16号第44条修订) (2)凡依据法例规定，某些材料须开放予公众查阅，如由适当的人或在其授权下，复制该等材料、向公众传播该等材料或向公众发放该等材料的复制品，而目的是让公众可在较方便的时间或地点查阅该等材料，或是为方便行使某项权利(该法例规定是为其行使而施加的)，则该项复制、传播或发放并不属侵犯版权。 (由 2022年第16号第44条修订) (3)凡依据法例规定须开放予公众查阅的材料，或法定登记册内的材料，载有一般人感兴趣的科学、技术、商业或经济方面的资料，如由适当的人或在其授权下，复制该等材料、向公众传播该等材料或向公众发放该等材料的复制品，而目的是使该等资料得以传布，则该项复制、传播或发放并不属侵犯版权。 (由 2022年第16号第44条修订) (4)行政长官可藉规例规定在规例指明的情况下，第(1)、(2)或(3)款只适用于按规例指明的方式而加有标记的复制品。 (由 1999年第22号第3条修订) (5)行政长官可藉规例规定第(1)至(3)款须按规例指明的程度及作出的变通而适用于以下项目，一如第(1)至(3)款适用于依据法例规定须开放予公众查阅的材料或法定登记册内的材料一样——(由 1999年第22号第3条修订) (a) (i)由规例所指明的国际组织开放予公众查阅的材料；或(ii)由规例所指明的人开放予公众查阅的材料，而该人乃根据香港是缔约一方的国际协议而在香港具有职能者；或(b)由规例所指明的国际组织备存的登记册。 (6)在本条中——法例规定(statutory requirement)指由条例或根据条例施加的规定； 法定登记册(statutory register)指依据由条例或根据条例施加的规定而备存的登记册、注册记录册或类似的名册； 适当的人(appropriate person)指须开放材料予公众查阅的人或备存法定登记册的人(视属何情况而定)。 [比照 1988 c. 48 s. 47 U.K.]", "56. Material open to public inspection or on official register (1) Where material is open to public inspection pursuant to a statutory requirement, or is on a statutory register, copyright is not infringed by the copying of so much of the material as contains factual information of any description, by or with the authority of the appropriate person, for a purpose which does not involve communicating the material to the public or issuing copies of the material to the public. (Amended 16 of 2022 s. 44) (2) Where material is open to public inspection pursuant to a statutory requirement, copyright is not infringed by copying the material, communicating the material to the public or issuing copies of the material to the public, by or with the authority of the appropriate person, for the purpose of enabling the material to be inspected at a more convenient time or place or otherwise facilitating the exercise of any right for the purpose of which the requirement is imposed. (Amended 16 of 2022 s. 44) (3) Where material which is open to public inspection pursuant to a statutory requirement, or which is on a statutory register, contains information about matters of general scientific, technical, commercial or economic interest, copyright is not infringed by copying the material, communicating the material to the public or issuing copies of the material to the public, by or with the a..."),
  source-statutes-cell("公共记录与官方材料使用的限制逻辑。"),

  "s.57",
  source-statutes-dual-cell("57. 在公务过程中供给政府的材料(由 2022年第16号第45条修订) (1)凡任何作品在公务过程中，已由版权拥有人或在版权拥有人的特许下为任何目的而供给政府，而记录或收录该作品的文件或其他实物，是由政府拥有或由政府保管或控制的，本条即适用。 (2)凡某作品已为某目的供给政府，则政府可为该目的或为版权拥有人可合理预料的有关连目的，复制该作品、向公众传播该作品或向公众发放该作品的复制品，而不属侵犯该作品的版权。 (3)如某作品先前已发表，但并非是凭借本条发表的，则政府不得凭借本条复制该作品、向公众传播该作品或向公众发放该作品的复制品。 (4)在第(1)款中， 公务(public business)包括政府进行的任何活动。 (5)本条在政府与版权拥有人订立的协议的规限下具有效力。 (由 2022年第16号第45条修订) [比照 1988 c. 48 s. 48 U.K.]", "57. Material provided to the Government in the course of public business (Amended 16 of 2022 s. 45) (1) This section applies where a work has in the course of public business been provided to the Government for any purpose, by or with the licence of the copyright owner and a document or other material thing recording or embodying the work is owned by or in the custody or control of the Government. (2) The Government may, for the purpose for which the work was provided to it, or any related purpose which could reasonably have been anticipated by the copyright owner, copy the work, communicate the work to the public or issue copies of the work to the public without infringing any copyright in the work. (3) The Government may not copy a work, communicate a work to the public or issue copies of a work to the public by virtue of this section if the work has previously been published otherwise than by virtue of this section. (4) In subsection (1) public business (公务) includes any activity carried on by the Government. (5) This section has effect subject to any agreement to the contrary between the Government and the copyright owner. (Amended 16 of 2022 s. 45) [cf. 1988 c. 48 s. 48 U.K.]"),
  source-statutes-cell("政府在特定条件下可复制/使用某些材料。"),

  "s.58",
  source-statutes-dual-cell("58. 公共纪录(1)开放予公众查阅的公共纪录内的材料可予复制，其复制品亦可供应予任何人，而该项复制及供应并不属侵犯版权。 (2)在本条中， 公共纪录(public record)指在立法会程序、司法程序或行政事务的过程中制作、收到或取得的属任何性质或类别的纪录，并包括构成纪录的一部分或附连于纪录或在其他方面与纪录有关连的证物和其他具关键性的证据，而该等纪录是由任何政府部门或须由任何政府部门保管，或可能转移给政府的任何部门或由其取得的。 (由 1999年第22号第3条修订) [比照 1988 c. 48 s. 49 U.K.]", "58. Public records (1) Material which is comprised in public records which are open to public inspection may be copied, and a copy may be supplied to any person without infringement of copyright. (2) In this section public records (公共纪录) means the records of any nature or description which have been made, received or acquired in the course of proceedings of the Legislative Council, judicial proceedings or executive transaction, together with the exhibits and other material evidence which form part of or are annexed to or are otherwise related to any record, which are or are required to be in the custody of, or which may be transferred to or be acquired by, any department of the Government. [cf. 1988 c. 48 s. 49 U.K.]"),
  source-statutes-cell("公共利益场景的例外条款，满足条件时可减轻侵权风险。"),

  "s.59",
  source-statutes-dual-cell("59. 根据法定权限所作出的作为(1)凡某条例(不论何时制定)明确授权作出某作为，则除非该条例另有规定，否则作出该作为不属侵犯版权。 (2)本条不得解释为令任何可根据或凭借任何条例而提出的法定权限免责辩护不得提出。 [比照 1988 c. 48 s. 50 U.K.]", "59. Acts done under statutory authority (1) Where the doing of a particular act is specifically authorized by an Ordinance, whenever enacted, then, unless the Ordinance provides otherwise, the doing of that act does not infringe copyright. (2) Nothing in this section is to be construed as excluding any defence of statutory authority otherwise available under or by virtue of any Ordinance. [cf. 1988 c. 48 s. 50 U.K.]"),
  source-statutes-cell("新闻信息传播的例外条款，报道用途下可提供抗辩空间。"),

  "s.60",
  source-statutes-dual-cell("60. 合法使用者可制作电脑程式的后备复制品(1)电脑程式的复制品的合法使用者如需要该程式的后备复制品供作他的合法用途，可制作该程式的后备复制品，而不属侵犯该程式的版权。 (2)就本条及第61条而言，某人如有合约权利使用某电脑程式，该人即为该程式的合法使用者。 (3)本条在任何与本条条文相反的协议的规限下具有效力。 [比照 1988 c. 48 s. 50A U.K.]", "60. Lawful user may make back-up copy of computer program (1) A lawful user of a copy of a computer program may make a back-up copy of the program without infringing the copyright in the program if it is necessary for him to have the back-up copy for the purposes of his lawful use. (2) For the purposes of this section and section 61 a person is a lawful user of a computer program if he has a contractual right to use the program. (3) This section has effect subject to any agreement to the contrary. [cf. 1988 c. 48 s. 50A U.K.]"),
  source-statutes-cell("作品附带出现场景的有限豁免。"),

  "s.61",
  source-statutes-dual-cell("61. 合法使用者可复制或改编程式(1)如电脑程式的复制品的合法使用者为其合法用途所需而复制或改编该程式，则他进行该项复制或改编并不属侵犯该程式的版权。 (2)如为合法使用电脑程式而有此需要，该电脑程式的复制品的合法使用者尤可为更正该程式的错误所需而复制或改编该程式。 (3)本条不适用于根据第60条而允许的任何复制或改编。 [比照 1988 c. 48 s. 50C U.K.]", "61. Lawful user may copy or adapt computer program (1) A lawful user of a copy of a computer program may copy or adapt the program without infringing the copyright in the program if the copying or adapting is necessary for his lawful use. (2) A lawful user of a copy of a computer program may, in particular, if it is necessary for the lawful use of the program, copy the program or adapt it for the purpose of correcting errors in it. (3) This section does not apply to any copying or adapting permitted under section 60 . [cf. 1988 c. 48 s. 50C U.K.]"),
  source-statutes-cell("公共场所艺术作品再利用的边界条款。"),

  "s.65",
  source-statutes-dual-cell("65. 因向公众传播作品而允许作出的某些作为(由 2022年第16号第46条修订)凡某作品向公众传播，而为让任何公众人士观看或聆听该作品，而在技术上需要制作一项短暂存在和附带的复制品，则尽管有第23条的规定，该项制作并不属侵犯该作品的版权。 (由 2022年第16号第46条修订)", "65. Certain acts permitted where works communicated to the public (Amended 16 of 2022 s. 46) Notwithstanding section 23 , copyright in a work is not infringed by the making of a transient and incidental copy which is technically required for the viewing or listening of the work by a member of the public to whom the work is communicated. (Amended 16 of 2022 s. 46)"),
  source-statutes-cell("计算机程序相关法定例外的关键条款，技术使用常会回到这里判断。"),

  "s.65A",
  source-statutes-dual-cell("65A. 由服务提供者作出的暂时复制(1)在符合以下规定的情况下，服务提供者制作及储存某作品的复制品，并不属侵犯该作品的版权——(a)制作及储存该复制品的唯一目的，是令该提供者能更有效率地透过网络传送该作品； (b)制作及储存该复制品是某科技过程中一个自动及必要的部分，而该过程并不改动该作品，亦不干扰合法使用科技以取得该作品的使用情况的数据； (c)储存该复制品是暂时的； (d)该提供者按照合理的行业常规，更新储存该复制品的数据库； (e)该提供者遵守接达该作品的条件(如有的话)；及(f)该提供者一旦实际知悉以下任何一项事实，便从速移除该复制品，或使其不能被接达——(i)该复制品是自某来源处制作的，而该作品已从该处被移除； (ii)该复制品是自某来源处制作的，而该作品已不能在该处被接达。 (2)在本条中——服务提供者(service provider)指藉电子设备或网络(或同时藉两者)，提供任何联线服务或为任何联线服务操作设施的人； 寄存(hosting)指应使用者的指令，在网络伺服器或任何电子检索系统中提供空间，以储存资料或材料； 资料搜寻工具(information location tools)指连接或指引使用者至某联线位置的工具，例如目录、索引、参考点、指示器或超文本连结； 路由选择(routing)指引导或选择传送数据的方法或路径； 联线服务(online service)包括——(a)传送使用者所选择的资料或材料，或为该资料或材料作出路由选择，或为该资料或材料的数码联线通讯提供连接，而该等数码联线通讯，是在使用者指明的超过一个点之间或之中进行的； (b)寄存使用者能接达的资料或材料； (c)在使用者能接达的系统或网络储存资料或材料； (d)藉使用资料搜寻工具，连接或指引使用者至某联线位置；及(e)向使用者提供联线社交网络服务。", "65A. Temporary reproduction by service providers (1) The copyright in a work is not infringed by the making and storage of a copy of the work by a service provider if— (a) the sole purpose of the making and storage is to enable more efficient transmission of the work by the provider through a network; (b) the making and storage forms an automatic and essential part of a technological process, and that process neither modifies the work, nor interferes with the lawful use of technology to obtain data on the use of the work; (c) the storage is temporary; (d) the provider updates the database in which the copy is stored in accordance with reasonable industry practice; (e) the provider complies with conditions (if any) on access to the work; and (f) the provider acts promptly to remove the copy or disable access to the copy in the event that either of the following facts comes to the provider’s actual knowledge— (i) the work has been removed from the original source from which the copy was made; (ii) access to the work at the original source from which the copy was made has been disabled. (2) In this section— hosting (寄存) means providing space on a network server or any electronic retrieval system for storage of information or material at the direction of a user; information location tools (资料搜寻工具) means tools such as directories, indexes, references, pointers, or hypertext links..."),
  source-statutes-cell("程序互操作/测试等技术场景补充例外。"),

  "s.89",
  source-statutes-dual-cell("89. 被识别为作者或导演的权利(1)具有版权的文学作品、戏剧作品、音乐作品或艺术作品的作者以及具有版权的影片的导演，在本条提及的情况下具有被识别为作品的作者或导演的权利；但除非该权利已按照第90条宣示，否则该权利并未遭侵犯。 (由 2007年第15号第22条修订) (2)凡有文学作品(但拟在音乐伴随下唱出或讲出的文字则除外)或戏剧作品——(a)作商业发表、公开表演或向公众传播；或(b)包括在某影片或声音纪录中，而该影片或声音纪录是向公众提供的，或该影片或声音纪录的复制品是向公众发放的， (由 2022年第16号第57条代替)则该作品的作者即具有被识别的权利；如有人将该作品的改编本作任何上述用途，则该权利包括被识别为该改编本所根据的原来作品的作者的权利。 (3)凡有音乐作品，或由拟在音乐伴随下唱出或讲出的文字所构成的文学作品——(a)作商业发表、公开表演或向公众传播； (b)被制成声音纪录，而该声音纪录是向公众提供的，或该声音纪录的复制品是向公众发放的；或(由 2022年第16号第57条代替) (c)包括在某影片的声带中，而该影片是公开放映的或是向公众提供的，或该影片的复制品是向公众发放的， (由 2022年第16号第57条代替)则该作品的作者即具有被识别的权利；如有人将该作品的改编本作任何上述用途，则该权利包括被识别为该改编本所根据的原来作品的作者的权利。 (4)凡有——(a)艺术作品作商业发表或公开陈列，或其影像向公众传播； (由 2007年第15号第22条修订) (b)艺术作品的影像包括在某影片中，而该影片是公开放映的或是向公众提供的，或该影片的复制品是向公众发放的；或(由 2022年第16号第57条代替) (c)建筑物形式或建筑物模型形式的建筑作品、雕塑品或美术工艺作品的艺术作品，是以平面美术作品表述或拍摄成照片的，而该平面美术作品或该照片是向公众提供的，或该平面美术作品的复制品或该照片的复制品是向公众发放的， 则该艺术作品的作者即具有被识别为作者的权利。 (5)建筑物形式的建筑作品的作者，亦有权在建成的有关建筑物上被识别为作者；如有超过一座建筑物依照该设计建成，则作者有权在第一座如此建成的建筑物上被识别为作者。 (6)凡公开放映或向公众传播某影片，或向公众发放某影片的复制品，则该影片的导演即具有被识别的权利。 (7)在——(a)影片或声音纪录的复制品作商业发表或向公众发放方面，作者或导演根据本条具有的权利为有权在每份该等复制品之上或之内被识别，在如此被识别并不适当的情况下，则有权以相当可能使取得该等复制品的人知悉其身分的其他方式被识别； (ab)影片或声音纪录向公众提供方面，作者或导演根据本条具有的权利为有权在该影片或声音纪录之上或之内被识别，在如此被识别并不适当的情况下，则有权以相当可能使取得该影片或声音纪录的人知悉该作者或导演身分的其他方式被识别； (由 2022年第16号第57条增补) (b)建筑物上识别身分方面，作者或导演根据本条具有的权利为有权以适当方法被识别，而该方法须能使进入或接近该建筑物的人看见该项识别的；及(c)任何其他方面，作者或导演根据本条具有的权利为有权以任何方式被识别，而该方式须是相当可能使观看或聆听有关表演、陈列、放映或传播的人知悉其身分的， (由 2007年第15号第22条修订)而在每种情况下，该项识别必...", "89. Right to be identified as author or director (1) The author of a copyright literary, dramatic, musical or artistic work, and the director of a copyright film, has the right to be identified as the author or director of the work in the circumstances mentioned in this section; but the right is not infringed unless it has been asserted in accordance with section 90 . (2) The author of a literary work (other than words intended to be sung or spoken with music) or a dramatic work has the right to be identified whenever— (a) the work is published commercially, performed in public or communicated to the public; or (b) a film or sound recording including the work is made available to the public, or copies of such a film or sound recording are issued to the public, (Replaced 16 of 2022 s. 57) and that right includes the right to be identified whenever any of those events occur in relation to an adaptation of the work as the author of the work from which the adaptation was made. (3) The author of a musical work, or a literary work consisting of words intended to be sung or spoken with music, has the right to be identified whenever— (a) the work is published commercially, performed in public or communicated to the public; (b) a sound recording of the work is made available to the public, or copies of such a sound recording are issued to the public; or (Replaced 16 of 2022 s. 57) (c..."),
  source-statutes-cell("作者/导演有被署名识别的权利。"),

  "s.90",
  source-statutes-dual-cell("90. 被识别的权利必须宣示(由 2007年第15号第23条修订) (1)除非第89条(被识别为作者或导演的权利)所赋予的权利已按照以下条文宣示，以对作出该条所提及作为的人就他作出该作为加以约束，否则任何人作出该条提及的作为，并不属侵犯该权利。 (2)该权利可藉以下方式一般性地宣示，或就任何指明的作为或指明类别的作为宣示——(由 2007年第15号第23条修订) (a)在转让作品的版权时，在转让版权的文书中加入述明作者或导演就该作品宣示其被识别的权利的陈述；或(b)由作者或导演签署的文书。 (3)被识别的权利可藉以下方式就公开陈列的艺术作品而宣示——(由 2007年第15号第23条修订) (a)凡作者或其他版权第一拥有人放弃对艺术作品原版的管有或放弃对艺术作品复制品(由他本人所制作或在他指示或控制下所制作的)的管有，则确保作者在当时已在该原版或复制品上被识别，或已在附连原版或复制品的框架、装裱或其他东西上被识别；或(b)在作者或版权第一拥有人授权制作作品复制品的特许中，加入一项由批出特许的人签署或由他人代其签署的书面陈述，该陈述指出如依据特许而公开陈列该复制品，则作者即宣示其被识别的权利。 (4)受根据第(2)或(3)款宣示被识别的权利约束的人为——(由 2007年第15号第23条修订) (a)就根据第(2)(a)款宣示权利而言，承让人及透过承让人提出申索的人(不论他是否知悉该项宣示)； (b)就根据第(2)(b)款宣示权利而言，得悉该项宣示的人； (c)就根据第(3)(a)款宣示权利而言，获得有关原版或复制品的人(不论有关识别是否仍存在或可看见)； (d)就根据第(3)(b)款宣示权利而言，特许持有人及获得依据特许而制作的复制品的人(不论他是否知悉该项宣示)。 (5)在就被识别的权利遭侵犯而进行的诉讼中，法庭在考虑补救时，须将宣示该权利的任何延误列为考虑因素。 (由 2007年第15号第23条修订) [比照 1988 c. 48 s. 78 U.K.]", "90. Requirement that right be asserted (1) A person does not infringe the right conferred by section 89 (right to be identified as author or director) by doing any of the acts mentioned in that section unless the right has been asserted in accordance with the following provisions so as to bind him in relation to that act. (2) The right may be asserted generally, or in relation to any specified act or description of acts— (a) on an assignment of copyright in the work, by including in the instrument effecting the assignment a statement that the author or director asserts in relation to that work his right to be identified; or (b) by instrument in writing signed by the author or director. (3) The right may also be asserted in relation to the public exhibition of an artistic work— (a) by securing that when the author or other first owner of copyright parts with possession of the original, or of a copy made by him or under his direction or control, the author is identified on the original or copy, or on a frame, mount or other thing to which it is attached; or (b) by including in a licence by which the author or other first owner of copyright authorizes the making of copies of the work a written statement signed by or on behalf of the person granting the licence that the author asserts his right to be identified in the event of the public exhibition of a copy made in pursuance of..."),
  source-statutes-cell("要主张署名权，通常要先依法作出宣示。"),

  "s.91",
  source-statutes-dual-cell("91. 权利的例外情况(1)第89条(被识别为作者或导演的权利)所赋予的权利有以下例外情况。 (2)该权利并不就以下类别的作品而适用——(a)电脑程式； (b)字体设计； (c)任何由电脑产生的作品。 (3)如作品版权原本是凭借第14(1)条(雇员的作品)而归属作者的雇主，则该权利不适用于由有关版权拥有人或在其授权下所作出的任何事情。 (4)如任何作为凭借以下任何条文而不属侵犯作品的版权，则该作为亦不属侵犯被识别的权利——(a)第39条(批评、评论、引用及报道和评论时事)； (由 2022年第16号第58条代替) (ab)第39A条(戏仿、讽刺、营造滑稽及模仿)； (由 2022年第16号第58条增补) (b)第40条(附带地将作品包括在某艺术作品、声音纪录、影片、广播或有线传播节目内)； (c)第41(3)条(试题)； (ca)第54B条(立法会)； (由 2007年第15号第24条增补) (d)第54条(司法程序)； (由 1999年第22号第3条修订；由 2007年第15号第24条修订) (e)第55(1)或(2)条(法定研讯)； (f)第66 或 75条(基于关于版权期限届满等的假设而允许作出的作为)。 (5)被识别的权利不就任何为报道时事的目的制作的作品而适用。 (由 2022年第16号第111条修订) (6)如制作文学作品、戏剧作品、音乐作品或艺术作品的目的是将该等作品于——(a)报章、杂志或相类期刊发表；或(b)百科全书、字典、词典、年鉴或其他参考性汇集作品发表， 或作者同意为于上述刊物发表而提供作品，则被识别的权利不就该等作品于上述刊物发表而适用。 (7)凡——(a)有政府版权或立法会版权存在于某作品被识别的权利不就该作品而适用；或(由 1999年第22号第3条修订) (b)某作品的版权凭借第188条而原本归属某国际组织，被识别的权利不就该作品而适用， 但如作者或导演以前已在该作品上或作品的已发表版本上被识别为作者或导演，则属例外。 [比照 1988 c. 48 s. 79 U.K.]", "91. Exceptions to right (1) The right conferred by section 89 (right to be identified as author or director) is subject to the following exceptions. (2) The right does not apply in relation to the following descriptions of work— (a) a computer program; (b) the design of a typeface; (c) any computer-generated work. (3) The right does not apply to anything done by or with the authority of the copyright owner where copyright in the work originally vested in the author’s employer by virtue of section 14(1) (employee works). (4) The right is not infringed by an act which by virtue of any of the following provisions would not infringe copyright in the work— (a) section 39 (criticism, review, quotation, and reporting and commenting on current events); (Replaced 16 of 2022 s. 58) (ab) section 39A (parody, satire, caricature and pastiche); (Added 16 of 2022 s. 58) (b) section 40 (incidental inclusion of work in an artistic work, sound recording, film, broadcast or cable programme); (c) section 41(3) (examination questions); (ca) section 54B (Legislative Council); (Added 15 of 2007 s. 24) (d) section 54 (judicial proceedings); (Amended 15 of 2007 s. 24) (e) section 55(1) or (2) (statutory inquiries); (f) section 66 or 75 (acts permitted on assumptions as to expiry of copyright, etc.). (5) The right does not apply in relation to any work made for the purpose of reporting current events..."),
  source-statutes-cell("署名权例外条款。"),

  "s.92",
  source-statutes-dual-cell("92. 反对作品受贬损处理的权利(1)具有版权的文学作品、戏剧作品、音乐作品或艺术作品的作者以及具有版权的影片的导演，在本条提及的情况下具有使其作品不受贬损处理的权利。 (2)就本条而言——(a)处理(treatment)作品指对作品进行任何增加、删除、修改或改编，但不包括——(i)翻译文学作品或戏剧作品；或(ii)将音乐作品编曲或改作而只涉及转调或转音域；及(b)如作品经处理后受歪曲或残缺不全，或在其他方面对作者或导演的荣誉或声誉具损害性，则该项处理属贬损处理， 而在以下条文中，凡提述作品受贬损处理，即须据此解释。 (3)就文学作品、戏剧作品或音乐作品而言，任何人如——(a)将受贬损处理的作品作商业发表、公开表演或向公众传播；或(由 2022年第16号第59条修订) (b)向公众提供受贬损处理的作品的影片或声音纪录，或向公众提供包括受贬损处理的作品在内的影片或声音纪录，或向公众发放该等影片或声音纪录的复制品， (由 2022年第16号第59条代替)该人即属侵犯该权利。 (4)就艺术作品而言，任何人如——(a)将受贬损处理的作品作商业发表或公开陈列，或将受贬损处理的作品的影像向公众传播； (由 2007年第15号第25条修订) (b)公开放映包括受贬损处理的作品的影像在内的影片，或向公众提供该影片或向公众发放该影片的复制品；或(c)向公众提供表述受贬损处理的下列作品的平面美术作品或照片或向公众发放该平面美术作品或照片的复制品——(由 2022年第16号第59条修订) (i)建筑物模型形式的建筑作品； (ii)雕塑品；或(iii)美术工艺作品， 该人即属侵犯该权利。 (由 2022年第16号第59条修订) (5)第(4)款不适用于建筑物形式的建筑作品；但如该等作品的作者已在该建筑物上被识别，而该建筑物属受贬损处理的标的物，则该作者有权要求除去该识别。 (6)就影片而言，任何人如——(a)将受贬损处理的影片公开放映或向公众传播；或(b)向公众发放受贬损处理的影片的复制品， 该人即属侵犯该权利。 (由 2022年第16号第59条修订) (7)因先前并非由作者或导演作出的处理而产生的某作品的部分凡受到处理，则该等部分如源出于该作者或导演或相当可能被视为该作者或导演的作品，本条所赋予的权利的适用范围，即扩及对该等部分的处理。 (8)本条在第93 及 94条(权利的例外情况及约制)的规限下具有效力。 [比照 1988 c. 48 s. 80 U.K.]", "92. Right to object to derogatory treatment of work (1) The author of a copyright literary, dramatic, musical or artistic work, and the director of a copyright film, has the right in the circumstances mentioned in this section not to have his work subjected to derogatory treatment. (2) For the purposes of this section— (a) treatment (处理) of a work means any addition to, deletion from or alteration to or adaptation of the work, other than— (i) a translation of a literary or dramatic work; or (ii) an arrangement or transcription of a musical work involving no more than a change of key or register; and (b) the treatment of a work is derogatory if it amounts to distortion or mutilation of the work or is otherwise prejudicial to the honour or reputation of the author or director, and in the following provisions of this section references to a derogatory treatment of a work are construed accordingly. (3) In the case of a literary, dramatic or musical work the right is infringed by a person who— (a) publishes commercially, performs in public or communicates to the public a derogatory treatment of the work; or (Amended 16 of 2022 s. 59) (b) makes available to the public a film or sound recording of, or including, a derogatory treatment of the work, or issues copies of such a film or sound recording to the public. (Replaced 16 of 2022 s. 59) (4) In the case of an artistic work the ri..."),
  source-statutes-cell("作者/导演可反对作品被贬损处理（歪曲、丑化等）。"),

  "s.94",
  source-statutes-dual-cell("94. 在某些情况下权利受约制(1)凡——(a)某作品凭借第14(1)条(在受雇工作期间制作的作品)而原本归属作者的雇主； (b)有政府版权或立法会版权存在于某作品；及(由 1999年第22号第3条修订) (c)某作品的版权凭借第188条而原本归属某国际组织， 则本条适用于该作品。 (2)第92条(反对作品受贬损处理的权利)所赋予的权利，不适用于由第(1)款所提述作品的版权拥有人或在其授权下就该等作品所作出的任何事情，但如作者或导演——(a)在有关作为作出之时被识别；或(b)先前已在作品的已发表复制品之内或之上被识别， 则属例外，而凡该权利在该情况下适用，则只要有足够的卸责声明，该权利不属遭侵犯。 [比照 1988 c. 48 s. 82 U.K.]", "94. Qualification of right in certain cases (1) This section applies to— (a) works in which copyright originally vested in the author’s employer by virtue of section 14(1) (works produced in course of employment); (b) works in which Government copyright or Legislative Council copyright subsists; and (c) works in which copyright originally vested in an international organization by virtue of section 188 . (2) The right conferred by section 92 (right to object to derogatory treatment of work) does not apply to anything done in relation to a work referred to in subsection (1) by or with the authority of the copyright owner unless the author or director— (a) is identified at the time of the relevant act; or (b) has previously been identified in or on published copies of the work, and where in such a case the right does apply, it is not infringed if there is a sufficient disclaimer. [cf. 1988 c. 48 s. 82 U.K.]"),
  source-statutes-cell("雇佣/政府/国际组织场景下精神权利限缩。"),

  "s.95",
  source-statutes-dual-cell("95. 管有侵犯权利物品或进行侵犯权利物品的交易而侵犯权利(1)任何人知道或有理由相信某物品属侵犯权利物品而将该物品作以下处置，即属侵犯第92条(反对作品受贬损处理的权利)所赋予的权利——(a)为任何贸易或业务的目的或在任何贸易或业务的过程中，管有该物品； (由 2000年第64号第4条代替) (b)将该物品出售、出租、要约出售或要约出租，或为出售或出租而展示该物品； (c)为任何贸易或业务的目的或在任何贸易或业务的过程中，公开陈列或分发该物品；或(由 2000年第64号第4条代替) (d)并非为任何贸易或业务的目的亦并非在任何贸易或业务的过程中，分发该物品致使作者或导演的荣誉或声誉蒙受不利影响。 (由 2000年第64号第4条修订；由 2007年第15号第26条修订) (1A)就第(1)(a)及(c)款而言，有关的贸易或业务是否包含经营侵犯权利物品并不具关键性。 (由 2000年第64号第4条增补) (2)侵犯权利物品(infringing article)指某项作品或该作品的复制品，而该作品或复制品——(a)曾受到第92条所指的贬损处理；及(b)曾经或相当可能在侵犯该权利的情况下属该条提及的作为的标的物。 [比照 1988 c. 48 s. 83 U.K.]", "95. Infringement of right by possessing or dealing with infringing article (1) The right conferred by section 92 (right to object to derogatory treatment of work) is also infringed by a person who— (a) possesses for the purpose of or in the course of any trade or business; (Replaced 64 of 2000 s. 4) (b) sells or lets for hire, or offers or exposes for sale or hire; (c) exhibits in public or distributes for the purpose of or in the course of any trade or business; or (Replaced 64 of 2000 s. 4) (d) distributes (otherwise than for the purpose of or in the course of any trade or business) so as to affect prejudicially the honour or reputation of the author or director, (Amended 64 of 2000 s. 4) an article which is, and which he knows or has reason to believe is, an infringing article. (Amended 15 of 2007 s.26) (1A) It is immaterial for the purpose of subsection (1)(a) and (c) whether or not the trade or business consists of dealing in infringing articles. (Added 64 of 2000 s. 4) (2) An infringing article (侵犯权利物品) means a work or a copy of a work which— (a) has been subjected to derogatory treatment within the meaning of section 92 ; and (b) has been or is likely to be the subject of any of the acts mentioned in that section in circumstances infringing that right. [cf. 1988 c. 48 s. 83 U.K.]"),
  source-statutes-cell("明知侵害精神权利仍交易也会侵权。"),

  "s.97",
  source-statutes-dual-cell("97. 权利的期限(1)第89条(被识别为作者或导演的权利)所赋予的权利以及第92条(反对作品受贬损处理的权利)所赋予的权利，在作品的版权存在的期间持续存在。 (2)第96条(虚假署名)所赋予的权利持续存在，直至有关的人死后20年为止。 [比照 1988 c. 48 s. 86 U.K.]", "97. Duration of rights (1) The rights conferred by section 89 (right to be identified as author or director) and section 92 (right to object to derogatory treatment of work) continue to subsist so long as copyright subsists in the work. (2) The right conferred by section 96 (false attribution) continues to subsist until 20 years after a person’s death. [cf. 1988 c. 48 s. 86 U.K.]"),
  source-statutes-cell("精神权利有独立期限，不完全等同财产权期限。"),

  "s.98",
  source-statutes-dual-cell("98. 同意及放弃权利(1)具有本分部所赋予的任何权利的人如同意作出某作为，则作出该作为并不属侵犯该权利。 (2)任何该等权利可藉由放弃权利的人签署的文书而放弃。 (3)放弃权利——(a)可关乎某特定作品、某指明类别的作品或一般地关乎所有作品，以及可关乎现存或未来的作品；及(b)可以是有条件或无条件的，亦可明示为可予撤回的， 而放弃权利如是为惠及该项放弃权利所关乎的作品的版权拥有人或准拥有人而作出的，则可推定该项放弃权利亦延伸而适用于该拥有人或准拥有人的特许持有人及所有权继承人，但如明示有相反的意愿，则属例外。 (4)本分部不得解释为摒除与任何关乎第(1)款提及的权利的非正式放弃或其他处理有关的一般合约法或不容反悔法的施行。 [比照 1988 c. 48 s. 87 U.K.]", "98. Consent and waiver of rights (1) It is not an infringement of any of the rights conferred by this Division to do any act to which the person entitled to the right has consented. (2) Any of those rights may be waived by instrument in writing signed by the person giving up the right. (3) A waiver— (a) may relate to a specific work, to works of a specified description or to works generally, and may relate to existing or future works; and (b) may be conditional or unconditional and may be expressed to be subject to revocation, and if made in favour of the owner or prospective owner of the copyright in the work or works to which it relates, it is presumed to extend to his licensees and successors in title unless a contrary intention is expressed. (4) Nothing in this Division is to be construed as excluding the operation of the general law of contract or estoppel in relation to an informal waiver or other transaction in relation to any of the rights mentioned in subsection (1). [cf. 1988 c. 48 s. 87 U.K.]"),
  source-statutes-cell("精神权利可以同意放弃，但最好有清楚书面文本。"),

  "s.99",
  source-statutes-dual-cell("99. 对合作作品适用的条文(1)就合作作品而言， 第89条(被识别为作者或导演的权利)所赋予的权利为每名合作作者被识别为合作作者的权利，而该权利须由每名合作作者按照第90条就其本身而宣示。 (由 2007年第15号第28条修订) (2)就合作作品而言， 第92条(反对作品受贬损处理的权利)所赋予的权利为每名合作作者的权利；如合作作者同意作品接受有关的处理，即属体现其权利。 (由 2007年第15号第28条修订) (3)合作作者中的其中一名作者根据第98条放弃该等权利，并不影响其他合作作者的该等权利。 (4)在第96条(虚假署名)提及的情况下——(a)任何有关合作作品的作者的虚假陈述；及(b)就单人作品虚假地以合作作者署名， 均属侵犯第96条所赋予的权利，而上述虚假署名亦属侵犯每名被署名(不论该署名是否正确)为任何类别作者的人的权利。 (5)本条条文经必要的修改后，亦适用于合作导演(或被指称为合作导演)的影片，一如该等条文适用于合作作品(或被指称为合作作品)的作品一样。 如某影片是由2名或多于2名导演合作制作，而且每名导演的贡献是与其他导演的贡献分不开的，该影片即属合作导演(jointly directed)的影片。 (编辑修订——2019年第2号编辑修订纪录) [比照 1988 c. 48 s. 88 U.K.]", "99. Application of provisions to joint works (1) The right conferred by section 89 (right to be identified as author or director) is, in the case of a work of joint authorship, a right of each joint author to be identified as a joint author and must be asserted in accordance with section 90 by each joint author in relation to himself. (2) The right conferred by section 92 (right to object to derogatory treatment of work) is, in the case of a work of joint authorship, a right of each joint author and his right is satisfied if he consents to the treatment in question. (3) A waiver under section 98 of those rights by one joint author does not affect the rights of the other joint authors. (4) The right conferred by section 96 (false attribution) is infringed, in the circumstances mentioned in that section— (a) by any false statement as to the authorship of a work of joint authorship; and (b) by the false attribution of joint authorship in relation to a work of sole authorship, and such a false attribution infringes the right of every person to whom authorship of any description is, whether rightly or wrongly, attributed. (5) The provisions of this section also apply (with any necessary adaptations) in relation to a film which was, or is alleged to have been, jointly directed, as they apply to a work which is, or is alleged to be, a work of joint authorship. A film is jointly dir..."),
  source-statutes-cell("合作作品下精神权利如何分别适用。"),

)