#import "../preamble.typ": source-statutes-plus-table, source-statutes-cell, source-statutes-dual-cell, h2
#h2([B. PDPO (Cap.486)])
#source-statutes-plus-table(
  [*Section*],
  [*Text*],
  [*Notes*],

  "DPP1",
  source-statutes-dual-cell("附表1第1原则——收集个人资料的目的及方式：资料须为与资料使用者职能或活动直接有关的合法目的而收集；收集须属必要而不过度，并以合法和在有关个案属公平的方式进行。", "Schedule 1, Principle 1—Purpose and manner of collection: personal data must be collected for a lawful purpose directly related to the data user’s function or activity; collection must be necessary, not excessive, and by lawful and fair means."),
  source-statutes-cell("未匹配到条文。先核对条号，再回抓。"),

  "DPP2",
  source-statutes-dual-cell("附表1第2原则——资料准确性及保留期间：须采取切实可行步骤确保资料准确；资料保存不得超过达成该用途（及直接相关用途）所需期间。", "Schedule 1, Principle 2—Accuracy and retention: all practicable steps must be taken to ensure accuracy; personal data must not be kept longer than necessary for the purpose (and directly related purpose)."),
  source-statutes-cell("未匹配到条文。先核对条号，再回抓。"),

  "DPP3",
  source-statutes-dual-cell("附表1第3原则——个人资料的使用：如无资料当事人的订明同意，个人资料不得用于“新目的”（即非收集时拟用目的或其直接相关目的）。", "Schedule 1, Principle 3—Use of personal data: personal data must not be used for a new purpose without the data subject’s prescribed consent."),
  source-statutes-cell("未匹配到条文。先核对条号，再回抓。"),

  "DPP4",
  source-statutes-dual-cell("附表1第4原则——个人资料保安：须采取所有切实可行步骤，保障所持有资料免受未经准许或意外的查阅、处理、删除、丧失或使用。", "Schedule 1, Principle 4—Security of personal data: all practicable steps must be taken to protect personal data against unauthorized or accidental access, processing, erasure, loss or use."),
  source-statutes-cell("未匹配到条文。先核对条号，再回抓。"),

  "DPP5",
  source-statutes-dual-cell("附表1第5原则——资讯须在一般情况下可提供：须采取切实可行步骤，让公众可知悉资料使用者的私隐政策、所持资料类别及主要使用目的。", "Schedule 1, Principle 5—Information to be generally available: practicable steps must be taken so people can ascertain the data user’s policies and practices, the kinds of data held, and the main purposes of use."),
  source-statutes-cell("未匹配到条文。先核对条号，再回抓。"),

  "DPP6",
  source-statutes-dual-cell("附表1第6原则——查阅个人资料：资料当事人有权查阅其个人资料、要求改正资料，并在被拒时获提供理由及提出反对。", "Schedule 1, Principle 6—Access to personal data: a data subject has rights of access and correction, and to be given reasons for refusal and to object."),
  source-statutes-cell("未匹配到条文。先核对条号，再回抓。"),

  "Part 6A",
  source-statutes-dual-cell("irst collection if, but only if, the data user concerned has complied with the provisions of data protection principle 1(3) in respect of the subsequent collection. 第6A部在直接促销中使用个人资料及提供个人资料以供用于直接促销(第6A部由 2012年第18号第21条增补) Part 6A Use of Personal Data in Direct Marketing and Provision of Personal Data for Use in Direct Marketing (Part 6A added 18 of 2012 s. 21) 35A. 第6A部的释义(1)在本部中——同意(consent)就在直接促销中使用个人资料而言，或就提供个人资料以供在直接促销中使用而言，包括表示不反对该项使用或提供； 回应途径(response channel)指由资料使用者根据第35C(2)(c)或 35J(2)(c)条向资料当事人提供的途径； 直接促销(direct marketing)指透过直接促销方法——(a)要约提供货品、设施或服务，或为该等货品、设施或服务可予提供而进行广告宣传；或(b)为慈善、文化、公益、康体、政治或其他目的索求捐赠或贡献； 直接促销方法(direct marketing means)指——(a)藉邮件、图文传真、电子邮件或其他形式的传讯，向指名特定人士送交资讯或货品；或(b)以特定人士为致电对象的电话通话； 促销标的(marketing subject)就直接促销而言， 指——(a)被要约提供或就其可予提供而进行广告宣传的任何货品、设施或服务；或(b)任何索求捐赠或贡献的目的； 许可种类个人资料(permitted kind of personal data)就资料当事人对某项拟进行的个人资料使用或提供的同意而言，指符合以下条件的种类的个人资料——(a)该种类的个人资料是在该当事人根据第35C(2)(b)(i)或 35J(2)(b)(ii)条获提供的资讯中指明的；及(b)该同意是就该种类的个人资料给予的； 许可类别人士(permitted class of persons)就资料当事人对某项拟进行的个人资料提供的同意而言，指符合以下条件的类别的人士——(a)该类别的人士是在该当事人根据第35J(2)(b)(iii)条获提供的资讯中指明的；及(b)该同意是就该类别的人士给予的； 许可类别促销标的(permitt", "irst collection if, but only if, the data user concerned has complied with the provisions of data protection principle 1(3) in respect of the subsequent collection. 第6A部在直接促销中使用个人资料及提供个人资料以供用于直接促销(第6A部由 2012年第18号第21条增补) Part 6A Use of Personal Data in Direct Marketing and Provision of Personal Data for Use in Direct Marketing (Part 6A added 18 of 2012 s. 21) 35A. 第6A部的释义(1)在本部中——同意(consent)就在直接促销中使用个人资料而言，或就提供个人资料以供在直接促销中使用而言，包括表示不反对该项使用或提供； 回应途径(response channel)指由资料使用者根据第35C(2)(c)或 35J(2)(c)条向资料当事人提供的途径； 直接促销(direct marketing)指透过直接促销方法——(a)要约提供货品、设施或服务，或为该等货品、设施或服务可予提供而进行广告宣传；或(b)为慈善、文化、公益、康体、政治或其他目的索求捐赠或贡献； 直接促销方法(direct marketing means)指——(a)藉邮件、图文传真、电子邮件或其他形式的传讯，向指名特定人士送交资讯或货品；或(b)以特定人士为致电对象的电话通话； 促销标的(marketing subject)就直接促销而言， 指——(a)被要约提供或就其可予提供而进行广告宣传的任何货品、设施或服务；或(b)任何索求捐赠或贡献的目的； 许可种类个人资料(permitted kind of personal data)就资料当事人对某项拟进行的个人资料使用或提供的同意而言，指符合以下条件的种类的个人资料——(a)该种类的个人资料是在该当事人根据第35C(2)(b)(i)或 35J(2)(b)(ii)条获提供的资讯中指明的；及(b)该同意是就该种类的个人资料给予的； 许可类别人士(permitted class of persons)就资料当事人对某项拟进行的个人资料提供的同意而言，指符合以下条件的类别的人士——(a)该类别的人士是在该当事人根据第35J(2)(b)(iii)条获提供的资讯中指明的；及(b)该同意是就该类别的人士给予的； 许可类别促销标的(permitt"),
  source-statutes-cell("直销专章：用或转交个人资料做直销前，通知与同意要做足。"),

  "Part VIII",
  source-statutes-dual-cell("第8部——豁免：在特定场景（如防止或侦测罪行、健康相关紧急情况、新闻活动、统计及研究等）下，部分保障资料原则或查阅/改正义务可获豁免。", "Part VIII—Exemptions: in specified contexts (for example prevention or detection of crime, health-related emergencies, news activities, and statistics/research), certain data protection principles or access/correction obligations may be exempted."),
  source-statutes-cell("未匹配到条文。先核对条号，再回抓。"),

  "s.15",
  source-statutes-dual-cell("15. 资料使用者登记册(1)专员须使用资料使用者申报表及变更通知的资讯，以备存及维持一份已呈交该等申报表的资料使用者的登记册。 (由 2012年第18号第9条代替) (2)登记册须——(a)采用数据库的形式；及(b)就每一名已呈交资料使用者申报表的资料使用者，载有在该申报表及任何变更通知中提供并且是专员认为合适的资讯的详情。 (由 2012年第18号第9条修订) (3)凡专员为在登记册与某资料使用者有关的范围内备存及维持登记册而合理地需要关于该资料使用者的订明资讯，专员可藉送达予该资料使用者的书面通知，要求该资料使用者呈交载有该等资讯并符合指明格式的通知，而该资料使用者须在专员所送达的通知中规定的期间(该期间不得迟于通知送达后的30日)内，以专员在通知中规定的方式，呈交该符合指明格式的通知。 (由 2012年第18号第9条修订) (4)凡根据第(3)款由某资料使用者呈交予专员的订明资讯在呈交后有所变更——(a)如(但只有在以下情况下)——(i)该等资讯在该款下的有关的通知中指明为本款所适用的资讯，及(ii)第(i)节所提述的通知载有或附有——(A)本款的文本一份；或(B)一项摘要说明本款施加予资料使用者的规定的陈述， 该资料使用者须向专员送达指明该等变更的书面通知；及(b)该资料使用者须在该等变更发生后的30日内向专员送达上述通知。 (4A)任何资料使用者明知或罔顾实情地在呈交予或送达专员的通知中，提供任何在要项上属虚假或具误导性的资讯，充作遵守第(3)或(4)款，即属犯罪，一经定罪，可处第3级罚款及监禁6个月。 (由 2012年第18号第9条增补) (5)如专员信纳某人已不再是资料使用者，他可从登记册中，删去其中所载的基于该人的资料使用者的身分而与他有关的任何详情。 (6)已不再是资料使用者的人，可藉向专员送达符合订明格式的通知，要求专员从登记册中，删去其中所载的基于该人的资料使用者的身分而与他有关的详情，而除非该人已撤回该项要求，专员须在收到该通知当日后的3个月内，依从该项要求。 (7)任何人在根据第(6)款送达专员的通知中，为了登记册所载的基于该人的资料使用者身分而与该人有关的详情得以删除，而提供任何在要项上属虚假或具误导性的资讯，即属犯罪，一经定罪，可处第3级罚款及监禁6个月。 (由 2012年第18号第9条增补)", "15. Register of data users (1) The Commissioner must keep and maintain a register of data users who have submitted data user returns, using information in those returns and in any change notices. (Replaced 18 of 2012 s. 9) (2) The register shall— (a) be in the form of a database; and (b) contain, in respect of each data user who has submitted a data user return, such particulars of the information supplied in that return and any change notice as the Commissioner thinks fit. (Amended 18 of 2012 s. 9) (3) The Commissioner may, by notice in writing served on a data user, require the data user to submit a notice in the specified form containing such prescribed information in relation to the data user as the Commissioner may reasonably require in order to keep and maintain the register in so far as it relates to that data user, and the data user shall so submit the second-mentioned notice within such period (being a period of not less than 30 days after service of the first-mentioned notice) and in such manner as the Commissioner requires in the first-mentioned notice. (Amended 18 of 2012 s. 9) (4) Where any prescribed information submitted to the Commissioner under subsection (3) by a data user changes subsequent to the submission, then the data user shall serve a notice in writing on the Commissioner specifying such change— (a) if, but only if— (i) such information is specified..."),
  source-statutes-cell("专员会据申报资料维护登记册。"),

  "s.16",
  source-statutes-dual-cell("16. 登记册的查阅(1)专员须提供设施以令登记册中所载详情——(a)可供任何人查阅； (b)可藉可观看及可阅读的形式供查阅； (c)可在一般办公时间内供查阅；及(d)可免费供查阅。 (2)如专员——(a)收到由某人提出的符合指明格式的申请；及(b)收到订明费用， 他须以书面提供登记册所载的关于该申请所指明的某资料使用者(或某类别的资料使用者)详情的复本。", "16. Inspection of register (1) The Commissioner shall provide facilities for making the particulars contained in the register available for inspection— (a) by any person; (b) in visible and legible form; (c) during ordinary office hours; and (d) free of charge. (2) The Commissioner shall— (a) on receipt of an application in the specified form from a person; and (b) on payment of the prescribed fee, provide a copy in writing of the particulars contained in the register in respect of the data user, or the class of data users, specified in the application."),
  source-statutes-cell("登记册可查阅，也可申请副本（通常要按程序缴费）。"),

  "s.18",
  source-statutes-dual-cell("18. 查阅资料要求(1)任何个人或代表一名个人的有关人士可提出内容如下的要求——(a)要求资料使用者告知他该使用者是否持有该名个人属其资料当事人的个人资料； (b)如该资料使用者持有该资料，要求该使用者提供一份该资料的复本。 (由 2012年第18号第2条修订) (2)在第(1)款(a)及(b)段下的查阅资料要求，须视为单一项要求，而本条例的条文须据此解释。 (3)在没有相反证据的情况下，第(1)款(a)段下的查阅资料要求须视为该款(a)及(b)段下的查阅资料要求，而本条例的条文(包括第(2)款)须据此解释。 (4)就个人资料而言，如某资料使用者——(由 2012年第18号第2条修订) (a)不是持有该资料的；但(b)控制该资料的使用，而控制的方式禁止实际持有该资料的另一资料使用者依从(不论是完全依从或部分依从)关乎该资料的查阅资料要求， (由 2012年第18号第2条修订)则他须当作持有该资料，而本条例的条文(包括本条)须据此解释。 (由 2012年第18号第2条修订) (5)任何人在查阅资料要求中，为了令有关资料使用者——(a)告知该人该资料使用者是否持有属该要求的标的之个人资料；及(b) (如适用)提供一份该资料的复本， 而提供在要项上属虚假或具误导性的资讯，即属犯罪。 (由 2012年第18号第11条增补) (6)任何人犯第(5)款所订罪行，一经定罪，可处第3级罚款及监禁6个月。 (由 2012年第18号第11条增补)", "18. Data access request (1) An individual, or a relevant person on behalf of an individual, may make a request— (a) to be informed by a data user whether the data user holds personal data of which the individual is the data subject; (b) if the data user holds such data, to be supplied by the data user with a copy of such data. (2) A data access request under both paragraphs of subsection (1) shall be treated as being a single request, and the provisions of this Ordinance shall be construed accordingly. (3) A data access request under paragraph (a) of subsection (1) may, in the absence of evidence to the contrary, be treated as being a data access request under both paragraphs of that subsection, and the provisions of this Ordinance (including subsection (2)) shall be construed accordingly. (4) A data user who, in relation to personal data— (a) does not hold the data; but (b) controls the use of the data in such a way as to prohibit the data user who does hold the data from complying (whether in whole or in part) with a data access request which relates to the data, shall be deemed to hold the data, and the provisions of this Ordinance (including this section) shall be construed accordingly. (Amended 18 of 2012 s. 11) (5) A person commits an offence if the person, in a data access request, supplies any information which is false or misleading in a material particular for the ..."),
  source-statutes-cell("个人可提出“查阅资料要求”，问你有没有持有其资料并索取副本。"),

  "s.19",
  source-statutes-dual-cell("19. 依从查阅资料要求(1)在符合第(2)款及第20 及 28(5)条的规定下，资料使用者须在收到由某人提出的查阅资料要求后的40日内，以下列方式，依从该项要求——(a)如该资料使用者持有属该项要求的标的之个人资料——(i)以书面告知提出要求者该资料使用者持有该资料；及(ii)提供一份该资料的复本；或(b)如该资料使用者并无持有属该项要求的标的之个人资料，以书面告知提出要求者该资料使用者并无持有该资料。 (由 2012年第18号第12条代替) (1A)尽管有第(1)(b)款的规定——(a)有人就香港警务处是否持有某名个人的任何刑事犯罪纪录，向香港警务处提出查阅资料要求；而(b)香港警务处并无持有该项纪录， 香港警务处须以下述方式依从该项要求︰ 在接获该要求后的40日内，以口头告知提出要求者香港警务处并无持有该项纪录。 (由 2012年第18号第12条增补) (2)凡资料使用者不能在第(1)或(1A)款指明的期间内依从查阅资料要求， 他——(由 2012年第18号第12条修订) (a)须在该期间届满前——(i)藉书面通知告知提出要求者他不能如此依从该项要求，以及其理由；及(ii)在他能依从该项要求的范围(如有的话)内，依从该项要求；及(b)须在该期间届满后，在切实可行的范围内尽快依从或尽快完全依从(视属何情况而定)该项要求。 (3)依从某项查阅资料要求而由资料使用者提供的个人资料复本——(a)须以收到该项要求时的该资料为准而提供，但该复本可——(由 2012年第18号第2条修订) (i)参照——(A)在收到该项要求的时间至供应该复本之时之间作出的；及(B)不论有否收到该项要求亦会作出的， 对该资料的处理；及(ii)在符合第(5)款的规定下，参照在收到该项要求的时间至供应该复本之时之间对该资料作出的改正； (b)在已对该资料作出(a)(ii)段所提述的任何改正的情况下，须附同一份通知，说明该资料已依据该段予以改正(或相似意思的字眼)；及(c)在切实可行范围内——(i)须是清楚易明的，但如该复本是一份文件的真实复本，而该份文件——(A)载有该资料；而(B)在表面上不是清楚易明的， 则属例外； (ii)在该资料使用者所使用的编码已获充分解说的情况下，须是容易理解的；及(iii) (A)除(B)分节另有规定外，须采用该项要求所指明的语文(可为中文或英文)；如无如此指明语文，则可采用提出该项要求所采用的语文(可为中文或英文)； (B)如(但只有在以下情况下)——(I)持有该资料所采用的语文，不是在该项要求所指明的语文或(如没有如此指明语文)提出该项要求所采用的语文(视属何情况而定)；而(II) (在符合第20(2)(b)条的规定下)该复本是载有该资料的文件的真实复本， 须采用该项要求所指明的语文以外的语文或(如没有如此指明语文)提出该项要求所采用的语文(视属何情况而定)以外的语文； (iv)在不损害第(iii)节的概括性原则下但在不抵触第(4)款的条文下，须采用该项要求所指明(如有指明的话)的形式或(如指明一种形式以上)其中一种形式； (v) (如第(iv)节不适用)须采用该资料使用者认为合适的形式。 (由 2012年第18号第2条修订) (4)凡——(a)查阅资料要求指明所寻求采用的为依从该项要求而提供的个人资料的复本而须采用的一种或多于一种形式；及(...", "19. Compliance with data access request (1) Subject to subsection (2) and sections 20 and 28(5) , a data user must comply with a data access request within 40 days after receiving the request by— (a) if the data user holds any personal data which is the subject of the request— (i) informing the requestor in writing that the data user holds the data; and (ii) supplying a copy of the data; or (b) if the data user does not hold any personal data which is the subject of the request, informing the requestor in writing that the data user does not hold the data. (Replaced 18 of 2012 s. 12) (1A) Despite subsection (1)(b) , if— (a) a data access request is made to the Hong Kong Police Force as to whether it holds any record of criminal conviction of an individual; and (b) it does not hold such record, it must comply with the request by informing the requestor orally, within 40 days after receiving the request, that it does not hold such record. (Added 18 of 2012 s. 12) (2) A data user who is unable to comply with a data access request within the period specified in subsection (1) or (1A) shall— (Amended 18 of 2012 s. 12) (a) before the expiration of that period— (i) by notice in writing inform the requestor that the data user is so unable and of the reasons why the data user is so unable; and (ii) comply with the request to the extent, if any, that the data user is able to comply wit..."),
  source-statutes-cell("收到查阅要求后有时限要回覆，不能无限拖延。"),

  "s.26",
  source-statutes-dual-cell("26. 删除不再需要的个人资料(1)凡资料使用者持有的个人资料是用于某目的(包括与该目的有直接关系的目的)，但已不再为该等目的而属有需要的，则除在以下情况外，该资料使用者须采取所有切实可行步骤删除该资料——(由 2012年第18号第2及17条修订) (a)该等删除根据任何法律是被禁止的；或(b)不删除该资料是符合公众利益(包括历史方面的利益)的。 (由 2012年第18号第2条修订) (2)为免生疑问，现声明——(a)即使任何其他资料使用者(前者)控制(不论是完全控制或部分控制)该资料的处理，持有有关资料的资料使用者(后者)须按照第(1)款，采取所有切实可行步骤删除个人资料； (由 2012年第18号第2及17条修订) (b)后者不得就该等删除而在前者为损害赔偿而提出的诉讼中负法律责任。", "26. Erasure of personal data no longer required (1) A data user must take all practicable steps to erase personal data held by the data user where the data is no longer required for the purpose (including any directly related purpose) for which the data was used unless— (Amended 18 of 2012 s. 17) (a) any such erasure is prohibited under any law; or (b) it is in the public interest (including historical interest) for the data not to be erased. (2) For the avoidance of doubt, it is hereby declared that— (a) a data user must take all practicable steps to erase personal data in accordance with subsection (1) notwithstanding that any other data user controls (whether in whole or in part) the processing of the data; (Amended 18 of 2012 s. 17) (b) the first-mentioned data user shall not be liable in an action for damages at the suit of the second-mentioned data user in respect of any such erasure."),
  source-statutes-cell("资料保存期不能无上限；目的达成后应删除或去识别化。"),

  "s.35B",
  source-statutes-dual-cell("35B. 适用范围本分部并不就要约提供以下服务或就有以下服务可予提供而进行广告宣传而适用——(a)由社会福利署营办、资助或津贴的社会服务； (b)由医院管理局或卫生署提供的医护服务；或(c)符合以下说明的任何其他社会或医护服务： 该项服务拟向某名个人提供，而如不向该名个人提供该项服务，便相当可能会对以下人士的身体或精神健康造成严重损害——(i)该名个人；或(ii)任何其他个人。", "35B. Application This Division does not apply in relation to the offering, or advertising of the availability, of— (a) social services run, subvented or subsidized by the Social Welfare Department; (b) health care services provided by the Hospital Authority or Department of Health; or (c) any other social or health care services which, if not provided, would be likely to cause serious harm to the physical or mental health of— (i) the individual to whom the services are intended to be provided; or (ii) any other individual."),
  source-statutes-cell("旧资料改作直销前，要补通知并给反对路径。"),

  "s.35C",
  source-statutes-dual-cell("35C. 资料使用者将个人资料用于直接促销前，须采取指明行动(1)除第35D条另有规定外，资料使用者如拟在直接促销中，使用某资料当事人的个人资料，须采取第(2)款指明的每一项行动。 (2)资料使用者须——(a)告知有关资料当事人——(i)该资料使用者拟如此使用有关个人资料；及(ii)该资料使用者须收到该当事人对该拟进行的使用的同意，否则不得如此使用该资料； (b)向该当事人提供关于该拟进行的使用的以下资讯——(i)拟使用的个人资料的种类；及(ii)该资料拟就什么类别的促销标的而使用；及(c)向该当事人提供一个途径，让该当事人可在无需向该资料使用者缴费的情况下，透过该途径，传达该当事人对上述的拟进行的使用的同意。 (3)不论个人资料是否由有关资料使用者从有关资料当事人收集的，第(1)款均适用。 (4)根据第(2)(a)及(b)款提供的资讯，须以易于理解的方式呈示，如属书面资讯，则亦须以易于阅读的方式呈示。 (5)除第35D条另有规定外，资料使用者未经采取第(2)款指明的每一项行动，而在直接促销中，使用某资料当事人的个人资料，即属犯罪，一经定罪，可处罚款$500,000及监禁3年。 (6)在为第(5)款所订罪行而提起的法律程序中，被控告的资料使用者如证明自己已采取所有合理预防措施，并已作出一切应作出的努力，以避免犯该罪行，即可以此作为免责辩护。 (7)凡有法律程序为第(5)款所订罪行而提起，在该程序之中，有关资料使用者负有举证责任，证明由于第35D条 ，本条并不适用。", "35C. Data user to take specified action before using personal data in direct marketing (1) Subject to section 35D , a data user who intends to use a data subject’s personal data in direct marketing must take each of the actions specified in subsection (2). (2) The data user must— (a) inform the data subject— (i) that the data user intends to so use the personal data; and (ii) that the data user may not so use the data unless the data user has received the data subject’s consent to the intended use; (b) provide the data subject with the following information in relation to the intended use— (i) the kinds of personal data to be used; and (ii) the classes of marketing subjects in relation to which the data is to be used; and (c) provide the data subject with a channel through which the data subject may, without charge by the data user, communicate the data subject’s consent to the intended use. (3) Subsection (1) applies irrespective of whether the personal data is collected from the data subject by the data user. (4) The information provided under subsection (2)(a) and (b) must be presented in a manner that is easily understandable and, if in written form, easily readable. (5) Subject to section 35D , a data user who uses a data subject’s personal data in direct marketing without taking each of the actions specified in subsection (2) commits an offence and is liable on convict..."),
  source-statutes-cell("用个人资料做直销前，通知内容和回覆渠道要合规。"),

  "s.35E",
  source-statutes-dual-cell("35E. 如无资料当事人同意，资料使用者不得将个人资料用于直接促销(1)已遵守第35C条的资料使用者不得在直接促销中，使用有关资料当事人的个人资料，但如以下条件获符合，则不在此限——(a)该资料使用者已收到该当事人对拟如此使用(如该资料使用者根据第35C(2)(b)条提供的资讯所描述者)该个人资料的同意，不论是一般的同意或是选择性的同意； (b) (如该项同意属口头同意)该资料使用者已自收到该项同意起计的14日内，向该当事人发出确认以下事宜的书面确认——(i)收到该项同意的日期； (ii)有关许可种类个人资料；及(iii)有关许可类别促销标的；及(c)该项使用符合该当事人的同意。 (2)就第(1)(c)款而言， 如——(a)有关个人资料属某许可种类个人资料；及(b)该资料是就某促销标的而使用，而该促销标的属某许可类别促销标的， 则该项使用即属符合该当事人的同意。 (3)资料当事人可透过回应途径或其他方法，向资料使用者传达对使用个人资料的同意。 (4)资料使用者违反第(1)款，即属犯罪，一经定罪，可处罚款$500,000及监禁3年。 (5)在为第(4)款所订罪行而提起的法律程序中，被控告的资料使用者如证明自己已采取所有合理预防措施，并已作出一切应作出的努力，以避免犯该罪行，即可以此作为免责辩护。", "35E. Data user must not use personal data in direct marketing without data subject’s consent (1) A data user who has complied with section 35C must not use the data subject’s personal data in direct marketing unless— (a) the data user has received the data subject’s consent to the intended use of personal data, as described in the information provided by the data user under section 35C(2)(b) , either generally or selectively; (b) if the consent is given orally, the data user has, within 14 days from receiving the consent, sent a written confirmation to the data subject, confirming— (i) the date of receipt of the consent; (ii) the permitted kind of personal data; and (iii) the permitted class of marketing subjects; and (c) the use is consistent with the data subject’s consent. (2) For the purposes of subsection (1)(c) , the use of personal data is consistent with the data subject’s consent if— (a) the personal data falls within a permitted kind of personal data; and (b) the marketing subject in relation to which the data is used falls within a permitted class of marketing subjects. (3) A data subject may communicate to a data user the consent to a use of personal data either through a response channel or other means. (4) A data user who contravenes subsection (1) commits an offence and is liable on conviction to a fine of $500,000 and to imprisonment for 3 years. (5) In any p..."),
  source-statutes-cell("当事人说不要直销后，资料使用者须停止。"),

  "s.35H",
  source-statutes-dual-cell("35H. 第3保障资料原则规定的对在直接促销中使用个人资料的订明同意尽管有第2(3)条的规定，凡根据第3保障资料原则，资料使用者在直接促销中使用某资料当事人的任何个人资料，须获该当事人的订明同意，该资料使用者如没有违反第35C 、 35E 或 35G条 ，即视为已取得该项同意。", "35H. Prescribed consent for using personal data in direct marketing under data protection principle 3 Despite section 2(3) , where a data user requires, under data protection principle 3, the prescribed consent of a data subject for using any personal data of the data subject in direct marketing, the data user is to be taken to have obtained the consent if the data user has not contravened section 35C , 35E or 35G ."),
  source-statutes-cell("直销违规的程序与举证补充条款。"),

  "s.35I",
  source-statutes-dual-cell("35I. 适用范围(1)如资料使用者并非为得益而将某资料当事人的个人资料，提供予另一人，以供该人用于要约提供以下服务或就以下服务可予提供而进行广告宣传——(a)由社会福利署营办、资助或津贴的社会服务； (b)由医院管理局或卫生署提供的医护服务；或(c)符合以下说明的任何其他社会或医护服务： 该项服务拟向某名个人提供，而如不向该名个人提供该项服务，便相当可能会对以下人士的身体或精神健康造成严重损害——(i)该名个人；或(ii)任何其他个人， 则本分部不适用。 (2)如资料使用者将某资料当事人的个人资料，提供予该资料使用者的代理人，以供该代理人在代表该资料使用者进行直接促销的过程中使用，则本分部不适用。", "35I. Application (1) This Division does not apply if a data user provides, otherwise than for gain, personal data of a data subject to another person for use by that other person in offering, or advertising the availability, of— (a) social services run, subvented or subsidized by the Social Welfare Department; (b) health care services provided by the Hospital Authority or Department of Health; or (c) any other social or health care services which, if not provided, would be likely to cause serious harm to the physical or mental health of— (i) the individual to whom the services are intended to be provided; or (ii) any other individual. (2) This Division does not apply if a data user provides personal data of a data subject to an agent of the data user for use by the agent in carrying out direct marketing on the data user’s behalf."),
  source-statutes-cell("直销违规责任的补充条款：把责任承担方式说得更细。"),

  "s.35J",
  source-statutes-dual-cell("35J. 资料使用者在提供个人资料前，须采取指明行动(1)资料使用者如拟将某资料当事人的个人资料提供予另一人，以供该人在直接促销中使用，该资料使用者须采取第(2)款指明的每一项行动。 (2)资料使用者须——(a)以书面告知有关资料当事人——(i)该资料使用者拟如此提供有关个人资料；及(ii)该资料使用者须收到该当事人对该拟进行的提供的书面同意，否则不得如此提供该资料； (b)向该当事人提供关于该拟进行的提供的以下书面资讯——(i) (如该资料是拟为得益而提供的)该资料是拟如此提供的； (ii)拟提供的个人资料的种类； (iii)该资料拟提供予什么类别的人士；及(iv)该资料拟就什么类别的促销标的而使用；及(c)向该当事人提供一个途径，让该当事人可在无需向该资料使用者缴费的情况下，透过该途径，以书面传达该当事人对上述的拟进行的提供的同意。 (3)不论个人资料是否由有关资料使用者从有关资料当事人收集的，第(1)款均适用。 (4)根据第(2)(a)及(b)款提供的资讯，须以易于理解和阅读的方式呈示。 (5)资料使用者未经采取第(2)款指明的每一项行动，而将某资料当事人的个人资料提供予另一人，以供该人在直接促销中使用，即属犯罪，一经定罪——(a)在该资料是为得益而提供的情况下，可处罚款$1,000,000及监禁5年；或(b)在该资料并非是为得益而提供的情况下，可处罚款$500,000及监禁3年。 (6)在为第(5)款所订罪行而提起的法律程序中，被控告的资料使用者如证明自己已采取所有合理预防措施，并已作出一切应作出的努力，以避免犯该罪行，即可以此作为免责辩护。", "35J. Data user to take specified action before providing personal data (1) A data user who intends to provide a data subject’s personal data to another person for use by that other person in direct marketing must take each of the actions specified in subsection (2). (2) The data user must— (a) inform the data subject in writing— (i) that the data user intends to so provide the personal data; and (ii) that the data user may not so provide the data unless the data user has received the data subject’s written consent to the intended provision; (b) provide the data subject with the following written information in relation to the intended provision— (i) if the data is to be provided for gain, that the data is to be so provided; (ii) the kinds of personal data to be provided; (iii) the classes of persons to which the data is to be provided; and (iv) the classes of marketing subjects in relation to which the data is to be used; and (c) provide the data subject with a channel through which the data subject may, without charge by the data user, communicate the data subject’s consent to the intended provision in writing. (3) Subsection (1) applies irrespective of whether the personal data is collected from the data subject by the data user. (4) The information provided under subsection (2)(a) and (b) must be presented in a manner that is easily understandable and easily readable. (5)..."),
  source-statutes-cell("把资料提供给他人做直销前，通知和同意门槛更高。"),

  "s.35K",
  source-statutes-dual-cell("35K. 如无资料当事人同意，资料使用者不得提供个人资料以供用于直接促销(1)已遵守第35J条的资料使用者，不得将有关资料当事人的个人资料提供予另一人，以供该人在直接促销中使用，但如以下条件获符合，则不在此限——(a)该资料使用者已收到该当事人对拟如此提供(如该资料使用者根据第35J(2)(b)条提供的资讯所描述者)该个人资料的书面同意，不论是一般的同意或是选择性的同意； (b) (如该资料使用者是为得益而提供该资料的)拟如此提供该资料的意向，已在第35J(2)(b)(i)条所指的资讯中指明；及(由 2014年第18号第172条修订) (c)该项提供符合该当事人的同意。 (2)就第(1)(c)款而言， 如——(a)有关个人资料属某许可种类个人资料； (b)获提供该资料的人属某许可类别人士；及(c)该资料是就某促销标的而使用，而该促销标的属某许可类别促销标的， 则该项提供即属符合该当事人的同意。 (3)资料当事人可透过回应途径或其他书面方法，向资料使用者传达对提供个人资料的同意。 (4)资料使用者违反第(1)款，即属犯罪，一经定罪——(a)在该资料使用者是为得益而提供有关个人资料的情况下，可处罚款$1,000,000及监禁5年；或(b)在该资料使用者并非是为得益而提供有关个人资料的情况下，可处罚款$500,000及监禁3年。 (5)在为第(4)款所订罪行而提起的法律程序中，被控告的资料使用者如证明自己已采取所有合理预防措施，并已作出一切应作出的努力，以避免犯该罪行，即可以此作为免责辩护。", "35K. Data user must not provide personal data for use in direct marketing without data subject’s consent (1) A data user who has complied with section 35J must not provide the data subject’s personal data to another person for use by that other person in direct marketing unless— (a) the data user has received the data subject’s written consent to the intended provision of personal data, as described in the information provided by the data user under section 35J(2)(b) , either generally or selectively; (b) if the data is provided for gain, the intention to so provide was specified in the information under section 35J(2)(b)(i) ; and (c) the provision is consistent with the data subject’s consent. (2) For the purposes of subsection (1)(c) , the provision of personal data is consistent with the data subject’s consent if— (a) the personal data falls within a permitted kind of personal data; (b) the person to whom the data is provided falls within a permitted class of persons; and (c) the marketing subject in relation to which the data is to be used falls within a permitted class of marketing subjects. (3) A data subject may communicate to a data user the consent to a provision of personal data either through a response channel or other written means. (4) A data user who contravenes subsection (1) commits an offence and is liable on conviction— (a) if the data user provides the pe..."),
  source-statutes-cell("未获有效同意就转交资料做直销，风险很高。"),

  "s.35L",
  source-statutes-dual-cell("35L. 资料当事人可要求资料使用者停止提供个人资料以供用于直接促销(1)获资料使用者根据第35J(2)(b)条提供资讯的资料当事人可随时要求该资料使用者——(a)停止将该当事人的个人资料提供予任何其他人，以供该人在直接促销中使用；及(b)通知获得如此提供该资料的任何人，停止在直接促销中使用该资料。 (2)不论有关资料当事人有否在较早前，同意有关个人资料的提供，第(1)款均适用。 (3)资料使用者如收到资料当事人根据第(1)款作出的要求，须在不向该当事人收费的情况下，依从该项要求。 (4)如资料使用者须按第(1)(b)款提述的要求，通知某人停止在直接促销中使用有关资料当事人的个人资料，该资料使用者须将该事宜以书面通知该人。 (5)某人如收到资料使用者根据第(4)款发出的书面通知，须按照该通知，停止在直接促销中使用有关个人资料。 (6)资料使用者违反第(3)款，即属犯罪，一经定罪——(a)在该项违反涉及为得益而提供某资料当事人的个人资料的情况下，可处罚款$1,000,000及监禁5年；或(b)在其他情况下，可处罚款$500,000及监禁3年。 (7)任何人违反第(5)款，即属犯罪，一经定罪，可处罚款$500,000及监禁3年。 (8)在为第(6)或(7)款所订罪行而提起的法律程序中，被控告的资料使用者或人士如证明自己已采取所有合理预防措施，并已作出一切应作出的努力，以避免犯该罪行，即可以此作为免责辩护。 (9)本条不影响第26条的施行。", "35L. Data subject may require data user to cease to provide personal data for use in direct marketing (1) A data subject who has been provided with information by a data user under section 35J(2)(b) may, at any time, require the data user— (a) to cease to provide the data subject’s personal data to any other person for use by that other person in direct marketing; and (b) to notify any person to whom the data has been so provided to cease to use the data in direct marketing. (2) Subsection (1) applies irrespective of whether the data subject has earlier given consent to the provision of the personal data. (3) A data user who receives a requirement from a data subject under subsection (1) must, without charge to the data subject, comply with the requirement. (4) If a data user is required to notify a person to cease to use a data subject’s personal data in direct marketing under a requirement referred to in subsection (1)(b) , the data user must so notify the person in writing. (5) A person who receives a written notification from a data user under subsection (4) must cease to use the personal data in direct marketing in accordance with the notification. (6) A data user who contravenes subsection (3) commits an offence and is liable on conviction— (a) if the contravention involves a provision of personal data of a data subject for gain, to a fine of $1,000,000 and to imprison..."),
  source-statutes-cell("违反直销相关条款可能触发刑责。"),

  "s.35M",
  source-statutes-dual-cell("35M. 第3保障资料原则规定的对提供个人资料以供用于直接促销的订明同意尽管有第2(3)条的规定，凡根据第3保障资料原则，资料使用者将某资料当事人的个人资料提供予另一人，以供在直接促销中使用，须获该当事人的订明同意，该资料使用者如没有违反第35J 、 35K 或 35L条 ，即视为已取得该项同意。", "35M. Prescribed consent for providing personal data for use in direct marketing under data protection principle 3 Despite section 2(3) , where a data user requires, under data protection principle 3, the prescribed consent of a data subject for providing any personal data of the data subject to another person for use in direct marketing, the data user is to be taken to have obtained the consent if the data user has not contravened section 35J , 35K or 35L ."),
  source-statutes-cell("直销章节的解释与衔接条款，用来处理条文之间怎么接轨。"),

  "s.36",
  source-statutes-dual-cell("36. 个人资料系统的视察在不损害第38条的概括性原则下，专员可对——(a)资料使用者所使用的任何个人资料系统；或(b)属于某资料使用者类别的资料使用者所使用的任何个人资料系统， 进行视察，目的在确定资讯以协助专员——(i)在——(A) (a)段适用时，向有关的资料使用者； (B) (b)段适用时，向有关的资料使用者所属于的一个类别的资料使用者， 作出建议；及(ii)作出关于促进有关的资料使用者或有关的资料使用者所属于的一个类别的资料使用者(视属何情况而定)遵守本条例的条文(尤其是各保障资料原则)的建议。", "36. Inspections of personal data systems Without prejudice to the generality of section 38 , the Commissioner may carry out an inspection of— (a) any personal data system used by a data user; or (b) any personal data system used by a data user belonging to a class of data users, for the purposes of ascertaining information to assist the Commissioner in making recommendations— (i) to— (A) where paragraph (a) is applicable, the relevant data user; (B) where paragraph (b) is applicable, the class of data users to which the relevant data user belongs; and (ii) relating to the promotion of compliance with the provisions of this Ordinance, in particular the data protection principles, by the relevant data user, or the class of data users to which the relevant data user belongs, as the case may be."),
  source-statutes-cell("专员可作视察，检查资料系统和合规状态。"),

  "s.38",
  source-statutes-dual-cell("38. 由专员进行的调查凡专员——(a)收到一项投诉；或(b)有合理理由相信有符合以下说明的作为或行为——(i)已经或正在(视属何情况而定)由资料使用者作出或从事的； (ii)关乎个人资料的；及(iii)可能属违反本条例下的规定的， 则——(i)如(a)段适用，除第39条另有规定外，专员须就有关的资料使用者进行调查，以确定在有关的投诉中指明的作为或行为是否属违反本条例下的规定； (ii)如(b)段适用，专员可就有关的资料使用者进行调查，以确定该段所提述的作为或行为是否属违反本条例下的规定。", "38. Investigations by Commissioner Where the Commissioner— (a) receives a complaint; or (b) has reasonable grounds to believe that an act or practice— (i) has been done or engaged in, or is being done or engaged in, as the case may be, by a data user; (ii) relates to personal data; and (iii) may be a contravention of a requirement under this Ordinance, then— (i) where paragraph (a) is applicable, the Commissioner shall, subject to section 39 , carry out an investigation in relation to the relevant data user to ascertain whether the act or practice specified in the complaint is a contravention of a requirement under this Ordinance; (ii) where paragraph (b) is applicable, the Commissioner may carry out an investigation in relation to the relevant data user to ascertain whether the act or practice referred to in that paragraph is a contravention of a requirement under this Ordinance."),
  source-statutes-cell("专员可展开调查，要求资料和解释。"),

  "s.39",
  source-statutes-dual-cell("39. 对由投诉引发的调查的限制(1)即使由本条例赋予专员的权力有其概括性，在以下情况下，专员可拒绝进行或决定终止由投诉引发的调查——(由 2012年第18号第22条修订) (a)投诉人(如投诉人是就某名个人而属有关人士的有关人士，则指该名个人)在超过紧接专员收到该项投诉当日之前的2年的时间内，已实际知悉有在该投诉中指明的作为或行为，但如专员信纳在该个案的所有情况下，进行或不终止(视属何情况而定)该项调查是恰当的，则属例外； (b)该项投诉是匿名者作出的； (c)投诉人的身分无法识辨或无法寻获投诉人； (d)就该项投诉所指明的作为或行为而言，以下所有条件均不获符合——(i)在有人作出或从事有关作为或行为(视属何情况而定)的任何时间——(A)投诉人(如投诉人是就某名个人而属有关人士的有关人士，则指该名个人)是居于香港的；或(B)有关的资料使用者能够在香港控制有关的个人资料的收集、持有、处理或使用或能够从香港行使该项控制的； (ii)在有人作出或从事有关作为或行为(视属何情况而定)的任何时间，投诉人(如投诉人是就某名个人而属有关人士的有关人士，则指该名个人)是在香港的； (iii)专员认为有关的作为或行为(视属何情况而定)可能损害投诉人(如投诉人是就某名个人而属有关人士的有关人士，则指该名个人)强制执行在香港获取或产生的权利或行使在香港获取或产生的特权； (由 2021年第32号第4条修订) (e)专员信纳有关的资料使用者在不少于紧接专员收到该项投诉当日之前的2年的期间内，不曾是资料使用者；或(由 2021年第32号第4条修订) (f)专员认为该项投诉关乎第64(1) 、 (3A)或(3C)条所订罪行，并决定进行第66C条所界定的指明调查。 (由 2021年第32号第4条增补) (2)如专员在顾及有关个案的所有情况后，信纳有以下情况，他可拒绝进行或决定终止由投诉引发的调查——(由 2012年第18号第22条修订) (a)该项投诉或一项在性质上大体与其相似的投诉已在先前引发一项调查，而专员在进行该项先前的调查后信纳没有违反本条例下的规定的情况； (b)在该项投诉中指明的作为或行为微不足道； (c)该项投诉属琐屑无聊或无理取闹，或不是真诚作出的； (ca)该项投诉所指明的作为或行为显示，该项投诉的主要标的事宜，与关乎个人资料的个人私隐无关；或(由 2012年第18号第22条增补) (d)因为任何其他理由，调查或进一步调查是不必要的。 (3)凡专员根据本条拒绝进行一项由投诉引发的调查，他须于收到该项投诉后的45日内，在切实可行范围内，尽快藉向投诉人送达一份附同第(4)款的文本的书面通知，告知该投诉人——(由 2012年第18号第22条修订) (a)该项拒绝一事；及(b)拒绝的理由。 (3A)如在一项由投诉引发的调查完成之前，专员决定终止该项调查，专员须在切实可行范围内，尽快向有关投诉人送达附有第(4)款的文本的书面通知，将以下事宜告知该投诉人——(a)该项决定；及(b)该项决定的理由。 (由 2012年第18号第22条增补) (4)反对——(a)第(3)款下的通知所指明的拒绝或第(3A)款下的通知所指明的终止而提出的上诉，可向行政上诉委员会提出；及(b)上述拒绝或终止而提出的上诉，可由获送达该项通知的投诉人提出；如投诉人是就某名个人而属有关人士的有关人士...", "39. Restrictions on investigations initiated by complaints (1) Notwithstanding the generality of the powers conferred on the Commissioner by this Ordinance, the Commissioner may refuse to carry out or decide to terminate an investigation initiated by a complaint if— (Amended 18 of 2012 s. 22) (a) the complainant (or, if the complainant is a relevant person, the individual in respect of whom the complainant is such a person) has had actual knowledge of the act or practice specified in the complaint for more than 2 years immediately preceding the date on which the Commissioner received the complaint, unless the Commissioner is satisfied that in all the circumstances of the case it is proper to carry out or not to terminate, as the case may be, the investigation; (b) the complaint is made anonymously; (c) the complainant cannot be identified or traced; (d) none of the following conditions is fulfilled in respect of the act or practice specified in the complaint— (i) either— (A) the complainant (or, if the complainant is a relevant person, the individual in respect of whom the complainant is such a person) was resident in Hong Kong; or (B) the relevant data user was able to control, in or from Hong Kong, the collection, holding, processing or use of the personal data concerned, at any time the act or practice was done or engaged in, as the case may be; (ii) the complainant (or, ..."),
  source-statutes-cell("专员在特定情形可拒查或终止查，边界在这里。"),

  "s.4",
  source-statutes-dual-cell("4. 保障资料原则资料使用者不得作出违反任何保障资料原则的作为或从事违反任何该等原则的行为，但如该作为或行为(视属何情况而定)是根据本条例规定须作出或进行或准许作出或进行的，则属例外。", "4. Data protection principles A data user shall not do an act, or engage in a practice, that contravenes a data protection principle unless the act or practice, as the case may be, is required or permitted under this Ordinance."),
  source-statutes-cell("适用范围与基本义务的起点条款，先确认你是否落在监管框架内。"),

  "s.50",
  source-statutes-dual-cell("50. 执行通知(1)如专员在完成一项调查后，认为有关资料使用者正在或已经违反本条例之下的规定，专员可向该资料使用者送达书面通知，指示该资料使用者纠正该项违反，以及(如适当的话)防止该项违反再发生。 (由 2012年第18号第28条代替) (1A)第(1)款所指的执行通知须——(a)述明专员持有第(1)款提述的意见，以及专员持有该意见的理由； (b)指明——(i)专员认为正在或已遭违反的规定；及(ii)构成该项违反的作为或不作为； (c)指明有关资料使用者须采取什么步骤(包括停止任何作为或行为)以纠正该项违反，以及(如适当的话)防止该项违反再发生； (d)指明须于何日或之前采取该等步骤；及(e)附有本条的文本。 (由 2012年第18号第28条增补) (1B)第(1A)(d)款指明的日期，不得早于第(7)款指明的可针对有关通知提出上诉的限期届满之时。 (由 2012年第18号第28条增补) (2)在决定是否送达执行通知时，专员须考虑该通知所关乎的违反，是否已对或是否相当可能会对属该违反所关乎的个人资料的资料当事人的个人，做成损害或困扰。 (由 2012年第18号第28条修订) (3)执行通知所指明的纠正该通知所关乎的违反的步骤，以及(如适当的话)防止该项违反再发生的步骤， 可——(a)在任何程度上，藉提述任何核准实务守则而拟订；及(b)按所需形式拟订，以让有关资料使用者可从不同的纠正方式中，以及(如适当的话)防止方式中，作出选择。 (由 2012年第18号第28条代替) (4)除第(5)款另有规定外，执行通知所指明的采取该通知所指明的步骤的限期不得在第(7)款所指明的上诉限期完结前届满，而如有该等上诉提出，在该上诉有决定或被撤回前不需采取该等步骤。 (5)如专员认为因为特殊情况，执行通知所指明的步骤因事态紧急而应即采取——(a)他可在该通知中加入一项有该意思的陈述及他持该意见的理由； (b)凡专员如此加入该项陈述，第(4)款即不适用，但该通知不得规定须在该通知送达当日起计的7日期间届满前采取该等步骤。 (6)专员可藉送达有关资料使用者的书面通知，撤销执行通知。 (7)有关资料使用者可在执行通知送达后14日内，向行政上诉委员会提出上诉反对该通知。 (8)凡专员——(a)在调查完成前的任何时间就有关资料使用者持第(1)款所提述的意见；并(b)同时认为因为特殊情况，执行通知因事态紧急而应即送达有关资料使用者， 则即使该项调查未完成，他可如此送达该通知，而在该等情况下——(i)专员须在不损害须加入该通知任何其他事宜的原则下，在该通知中指明他持(b)段所提述的意见的理由；而(ii)本条例其他条文(包括本条)须据此解释。", "50. Enforcement notices (1) If, following the completion of an investigation, the Commissioner is of the opinion that the relevant data user is contravening or has contravened a requirement under this Ordinance, the Commissioner may serve on the data user a notice in writing, directing the data user to remedy and, if appropriate, prevent any recurrence of the contravention. (Replaced 18 of 2012 s. 28) (1A) An enforcement notice under subsection (1) must— (a) state that the Commissioner is of the opinion referred to in subsection (1) and the reason for that opinion; (b) specify— (i) the requirement which, in the opinion of the Commissioner, is being or has been contravened; and (ii) the act or omission that constitutes the contravention; (c) specify the steps that the data user must take (including ceasing any act or practice) to remedy and, if appropriate, prevent any recurrence of the contravention; (d) specify the date on or before which the steps must be taken; and (e) be accompanied by a copy of this section. (Added 18 of 2012 s. 28) (1B) The date specified in subsection (1A)(d) must be a date which is not earlier than the expiry of the period specified in subsection (7) within which an appeal against the notice may be made. (Added 18 of 2012 s. 28) (2) In deciding whether to serve an enforcement notice the Commissioner shall consider whether the contravention to which t..."),
  source-statutes-cell("违规后的罪责或程序后果条款，决定违法后会走到哪一步。"),

  "s.50B",
  source-statutes-dual-cell("50B. 关乎没有遵从专员的要求等的罪行(1)任何人如有以下情况，即属犯罪——(a)该人无合法辩解而妨碍、阻挠或抗拒专员或任何订明人员执行其在本部之下的职能(或行使其在本部之下的权力)； (b)该人无合法辩解而没有遵从专员或任何订明人员根据本部作出的合法要求；或(c)该人在专员或在任何订明人员执行本部之下的职能或行使本部之下的权力的过程中——(i)向专员或该人员作出该人知道属虚假或不相信属真实的陈述；或(ii)以其他方式在知情下误导专员或该人员。 (2)任何人犯第(1)款所订罪行，一经定罪，可处第3级罚款及监禁6个月。 (由 2012年第18号第29条增补)", "50B. Offences relating to failure to comply with requirements of Commissioner etc. (1) A person commits an offence if the person— (a) without lawful excuse, obstructs, hinders or resists the Commissioner or a prescribed officer in performing the functions or exercising the powers of the Commissioner or the officer under this Part; (b) without lawful excuse, fails to comply with any lawful requirement of the Commissioner or a prescribed officer under this Part; or (c) in the course of the performance or exercise by the Commissioner or a prescribed officer of functions or powers under this Part— (i) makes to the Commissioner or the officer a statement which the person knows to be false or does not believe to be true; or (ii) otherwise knowingly misleads the Commissioner or the officer. (2) A person who commits an offence under subsection (1) is liable on conviction to a fine at level 3 and to imprisonment for 6 months. (Added 18 of 2012 s. 29)"),
  source-statutes-cell("与执行通知衔接的进一步执法条款。"),

  "s.52",
  source-statutes-dual-cell("52. 家居用途由个人持有并——(a)只与其私人事务、家庭事务或家居事务有关的个人资料；或(b)只是为消闲目的而如此持有的个人资料， 获豁免而不受各保障资料原则、第4和5部及第36和38(b)条的条文所管限。 (编辑修订——2013年第1号编辑修订纪录)", "52. Domestic purposes Personal data held by an individual and— (a) concerned only with the management of his personal, family or household affairs; or (b) so held only for recreational purposes, is exempt from the provisions of the data protection principles, Parts 4 and 5 and sections 36 and 38(b) . (Amended 18 of 2012 s. 2 ; E.R. 1 of 2013)"),
  source-statutes-cell("法庭程序与执行安排的辅助条款，主要解决“怎么执行到位”。"),

  "s.53",
  source-statutes-dual-cell("53. 雇佣——职工策划包含与——(a)填补任何系列的现正出缺或可能会出缺的雇佣职位；或(b)终止任何组别的个人的雇用， 的职工策划建议有关的资讯的个人资料获豁免而不受第6保障资料原则及第18(1)(b)条的条文所管限。", "53. Employment—staff planning Personal data which consists of information relevant to any staff planning proposal to— (Amended 18 of 2012 s. 2) (a) fill any series of positions of employment which are presently, or may become, unfilled; or (b) cease any group of individuals’ employment, is exempt from the provisions of data protection principle 6 and section 18(1)(b) . (Amended 18 of 2012 s. 2)"),
  source-statutes-cell("执法程序中的补充权力或限制。"),

  "s.57",
  source-statutes-dual-cell("57. 关于香港的保安等(1)凡个人资料是为保障关于香港的保安、防卫或国际关系的目的而由政府或代政府持有，则如第6保障资料原则及第18(1)(b)条的条文适用于该资料，便相当可能会损害本款所述的任何事宜的话，该资料获豁免而不受该等条文所管限。 (由 2012年第18号第2条修订) (2)凡——(a)个人资料是为第(1)款所提述的目的而使用(不论该资料是否为该等目的而持有)；及(b)第3保障资料原则的条文就该等使用而适用便相当可能会损害该款所提述的任何事宜， 该资料获豁免而不受第3保障资料原则的条文所管限，而在为任何人违反任何该等条文而针对他进行的法律程序中，如该人证明他当时有合理理由相信不如此使用该资料便相当可能会损害任何该等事宜，即为免责辩护。 (由 2012年第18号第2条修订) (3)就任何个人资料是否需有第(1)款下的豁免或曾否在任何时间需有第(1)款下的豁免的问题，可由行政长官或政务司司长决定，而一份由行政长官或政务司司长签署并证明需有或曾在任何时间需有该项豁免的证明书，即为该事实的证据。 (由 1997年第362号法律公告修订；由 1999年第34号第3条修订) (4)就第(2)款而言，一份由行政长官或政务司司长签署的证明个人资料是为或曾为第(1)款所提述的任何目的而使用的证明书，即为该事实的证据。 (由 1997年第362号法律公告修订；由 1999年第34号第3条修订) (5)行政长官或政务司司长可在第(3)或(4)款所提述的证明书中，就该证明书所关乎的个人资料及为该证明书所指明的理由，指示专员不得进行视察或调查，而在此情况下，专员须遵从该项指示。 (由 1997年第362号法律公告修订；由 1999年第34号第3条修订) (6)看来是第(3)或(4)款所提述的证明书的文件，须获收取为证据，而在没有相反证据的情况下，该文件须当作为该等证明书。 (7)在本条中——保安(security)包括防止或排拒无权进入香港及留在香港的人(包括按照《入境条例》(第115章)的条文被扣留的人)进入香港及留在香港； (由 1997年第80号第103(1)条修订)国际关系(international relations)包括与任何国际组织的关系。", "57. Security, etc. in respect of Hong Kong (1) Personal data held by or on behalf of the Government for the purposes of safeguarding security, defence or international relations in respect of Hong Kong is exempt from the provisions of data protection principle 6 and section 18(1)(b) where the application of those provisions to the data would be likely to prejudice any of the matters referred to in this subsection. (Amended 18 of 2012 s. 2) (2) Personal data is exempt from the provisions of data protection principle 3 in any case in which— (Amended 18 of 2012 s. 2) (a) the use of the data is for any of the purposes referred to in subsection (1) (and whether or not the data is held for any of those purposes); and (Amended 18 of 2012 s. 2) (b) the application of those provisions in relation to such use would be likely to prejudice any of the matters referred to in that subsection, and in any proceedings against any person for a contravention of any of those provisions it shall be a defence to show that he had reasonable grounds for believing that failure to so use the data would have been likely to prejudice any of those matters. (3) Any question whether an exemption under subsection (1) is or at any time was required in respect of any personal data may be determined by the Chief Executive or Chief Secretary for Administration; and a certificate signed by the Chief Executive or..."),
  source-statutes-cell("与调查或执行相关的程序补充条款。"),

  "s.59",
  source-statutes-dual-cell("59. 健康(1)与有关的资料当事人的身体健康或精神健康有关的个人资料，获豁免而不受以下任何或所有条文所管限——(由 2012年第18号第32条修订) (a)第6保障资料原则及第18(1)(b)条的条文； (b)第3保障资料原则的条文， 但上述豁免仅在以下情况适用——(i)该等条文适用于该资料便相当可能会对该资料当事人的身体健康或精神健康造成严重损害；或(由 2012年第18号第2条修订) (ii)该等条文适用于该资料便相当可能会对任何其他个人的身体健康或精神健康造成严重损害。 (由 2012年第18号第2条修订) (2)如第3保障资料原则的条文适用于关乎某资料当事人的身分或所在的个人资料，便相当可能会对——(a)该资料当事人的身体或精神健康造成严重损害；或(b)任何其他个人的身体或精神健康造成严重损害， 则该资料获豁免而不受该等条文所管限。 (由 2012年第18号第32条增补)", "59. Health (1) Personal data relating to the physical or mental health of the data subject is exempt from the provisions of either or both of— (Amended 18 of 2012 s. 32) (a) data protection principle 6 and section 18(1)(b) ; (b) data protection principle 3, in any case in which the application of those provisions to the data would be likely to cause serious harm to the physical or mental health of— (i) the data subject; or (ii) any other individual. (2) Personal data relating to the identity or location of a data subject is exempt from the provisions of data protection principle 3 if the application of those provisions to the data would be likely to cause serious harm to the physical or mental health of— (a) the data subject; or (b) any other individual. (Added 18 of 2012 s. 32)"),
  source-statutes-cell("健康与紧急情境的豁免条款，重点在“必要性”和情境紧迫度。"),

  "s.62",
  source-statutes-dual-cell("62. 统计及研究在以下情况，个人资料获豁免而不受第3保障资料原则的条文所管限——(a)该资料将会用于制备统计数字或进行研究； (b)该资料不会用于任何其他目的；及(c)所得的统计数字或研究成果不会以识辨各有关的资料当事人或其中任何人的身分的形式提供。 (由 2012年第18号第2条修订)", "62. Statistics and research Personal data is exempt from the provisions of data protection principle 3 where— (Amended 18 of 2012 s. 2) (a) the data is to be used for preparing statistics or carrying out research; (b) the data is not to be used for any other purpose; and (c) the resulting statistics or results of the research are not made available in a form which identifies the data subjects or any of them. (Amended 18 of 2012 s. 2)"),
  source-statutes-cell("调查与监管场景的细化豁免条款，常和 s.61 一起看。"),

  "s.64",
  source-statutes-dual-cell("64. 在未获同意下披露个人资料属罪行(由 2021年第32号第6条修订) (1)任何人披露未经资料使用者同意而取自该资料使用者的某资料当事人的任何个人资料，而该项披露是出于以下意图的，该人即属犯罪——(a)获取金钱得益或其他财产得益，不论是为了令该人或另一人受惠而获取；或(b)导致该当事人蒙受金钱损失或其他财产损失。 (2) (由 2021年第32号第6条废除) (3)任何人犯第(1)款所订罪行，一经定罪，可处罚款$1,000,000及监禁5年。 (由 2021年第32号第6条修订) (3A)如任何人(披露者)在未获资料当事人的相关同意下，披露该当事人的个人资料， 而——(a)披露者的意图，是导致该当事人或其任何家人蒙受任何指明伤害；或(b)披露者罔顾是否会(或相当可能会)导致该当事人或其任何家人蒙受任何指明伤害， 披露者即属犯罪。 (由 2021年第32号第6条增补) (3B)任何人犯第(3A)款所订罪行，一经定罪，可处第6级罚款及监禁2年。 (由 2021年第32号第6条增补) (3C)如——(a)任何人(披露者)在未获资料当事人的相关同意下，披露该当事人的个人资料， 而——(i)披露者的意图，是导致该当事人或其任何家人蒙受任何指明伤害；或(ii)披露者罔顾是否会(或相当可能会)导致该当事人或其任何家人蒙受任何指明伤害；及(b)该项披露导致该当事人或其任何家人蒙受任何指明伤害， 披露者即属犯罪。 (由 2021年第32号第6条增补) (3D)任何人犯第(3C)款所订罪行，一经循公诉程序定罪，可处罚款$1,000,000及监禁5年。 (由 2021年第32号第6条增补) (4)在第(1)、(3A)或(3C)款所订罪行的法律程序中，被控告的人如确立以下事宜，即为免责辩护——(由 2021年第32号第6条代替) (a)该人合理地相信，有关披露对防止或侦测罪行属必要； (b)任何成文法则、法律规则或法院命令规定作出或授权作出有关披露，或根据任何成文法则而规定作出或授权作出有关披露； (c)该人合理地相信有关披露是——(由 2021年第32号第6条修订) (i)如属第(1)款所订罪行——在获得有关资料使用者的同意下作出的；或(ii)如属第(3A)或(3C)款所订罪行——在获得有关资料当事人的相关同意下作出的；或(由 2021年第32号第6条修订) (d)该人——(i)纯粹为合法的、 第61(3)条所界定的新闻活动(或与之直接相关的活动)，而披露有关个人资料；及(由 2021年第32号第6条代替) (ii)有合理理由相信，发表或播放该个人资料，是符合公众利益的。 (5)在以下情况下，就第(4)款所指的免责辩护而需要确立的事宜，须视作已由某人确立——(a)有足够证据，就该事宜带出争论点；及(b)控方没有提出足以排除合理疑点的证据，证明并非如此。 (由 2021年第32号第6条增补) (6)在本条中——指明伤害(specified harm)就某人而言，指——(a)对该人的滋扰、骚扰、缠扰、威胁或恐吓； (b)对该人的身体伤害或心理伤害； (c)导致该人合理地担心其安全或福祉的伤害；或(d)该人的财产受损； 相关同意(relevant consent)就某资料当事人而言，指——(a)如该当事人属第2(1)条中有关人士的定义(a)、(b)或(c)段所描述的...", "64. Offences for disclosing personal data without consent (Amended 32 of 2021 s. 6) (1) A person commits an offence if the person discloses any personal data of a data subject which was obtained from a data user without the data user’s consent, with an intent— (a) to obtain gain in money or other property, whether for the benefit of the person or another person; or (b) to cause loss in money or other property to the data subject. (2) (Repealed 32 of 2021 s. 6) (3) A person who commits an offence under subsection (1) is liable on conviction to a fine of $1,000,000 and to imprisonment for 5 years. (Amended 32 of 2021 s. 6) (3A) A person commits an offence if the person discloses any personal data of a data subject without the relevant consent of the data subject— (a) with an intent to cause any specified harm to the data subject or any family member of the data subject; or (b) being reckless as to whether any specified harm would be, or would likely be, caused to the data subject or any family member of the data subject. (Added 32 of 2021 s. 6) (3B) A person who commits an offence under subsection (3A) is liable on conviction to a fine at level 6 and to imprisonment for 2 years. (Added 32 of 2021 s. 6) (3C) A person commits an offence if— (a) the person discloses any personal data of a data subject without the relevant consent of the data subject— (i) with an intent to cause a..."),
  source-statutes-cell("违法后责任追究条款：谁承担、怎么追责，这里给出框架。"),

  "s.65",
  source-statutes-dual-cell("65. 雇主及主事人的法律责任(1)任何人在其受雇用中所作出的任何作为或所从事的任何行为，就本条例而言须视为亦是由其雇主所作出或从事的，不论其雇主是否知悉或批准他作出该作为或从事该行为。 (2)任何作为另一人的代理人并获该另一人授权(不论是明示或默示，亦不论是事前或事后授权)的人所作出的任何作为或所从事的任何行为，就本条例而言须视为亦是由该另一人作出或从事的。 (3)在根据本条例对任何人就其雇员被指称作出的作为或从事的行为(视属何情况而定)而提出的法律程序中，该人如证明他已采取切实可行的步骤，以防止该雇员作出该作为或从事该行为或在其受雇用过程中作出该类作为或从事该类行为，即为免责辩护。 (4)为免生疑问，现声明︰本条不就刑事法律程序而适用。", "65. Liability of employers and principals (1) Any act done or practice engaged in by a person in the course of his employment shall be treated for the purposes of this Ordinance as done or engaged in by his employer as well as by him, whether or not it was done or engaged in with the employer’s knowledge or approval. (2) Any act done or practice engaged in by a person as agent for another person with the authority (whether express or implied, and whether precedent or subsequent) of that other person shall be treated for the purposes of this Ordinance as done or engaged in by that other person as well as by him. (3) In proceedings brought under this Ordinance against any person in respect of an act or practice alleged to have been done or engaged in, as the case may be, by an employee of his it shall be a defence for that person to prove that he took such steps as were practicable to prevent the employee from doing that act or engaging in that practice, or from doing or engaging in, in the course of his employment, acts or practices, as the case may be, of that description. (4) For the avoidance of doubt, it is hereby declared that this section shall not apply for the purposes of any criminal proceedings."),
  source-statutes-cell("刑责层级与处罚框架补充条款。"),

  "s.66B",
  source-statutes-dual-cell("66B. 专员可就法律程序给予协助(1)根据第66条可提起法律程序以寻求补偿的人可向专员提出申请，要求就该程序给予协助。 (2)专员可考虑第(1)款所指的申请，如专员认为合适，可批准申请，在以下情况下，专员尤其可批准申请——(a)有关个案带出一个原则性问题；或(b)在顾及有关个案的复杂性、申请人相对于答辩人或受牵涉的另一人的位置或任何其他事宜下，期望申请人在没有协助下处理有关个案，是不合理的。 (3)专员根据本条给予的协助可包括——(a)提供意见； (b)安排由律师或大律师提供意见或协助； (c)安排由任何人代表行事，包括通常由律师或大律师在法律程序的初步步骤或附带步骤中给予的协助，或在达致或执行和解以避免或结束法律程序中给予的协助；及(d)专员认为适当的其他形式的协助。 (4)除了在根据按照《区域法院条例》(第336章)第73F条订立的规则准许的范围内，第(3)(c)款不影响规管什么种类的人可在法律程序中出庭、进行法律程序、抗辩及向法庭陈词的法律及常规。 (5)如专员因根据本条向申请人提供协助而招致开支，该等开支(以《法院规则》所订明的方式评定或评核者)的追讨构成使专员受益的对以下项目的第一押记——(a)须由任何其他人(不须凭借区域法院的判决或命令、协议或其他依据)就该项协助所关乎的事宜而付予该申请人的任何讼费或费用；及(b)在就该事宜达致避免或结束任何法律程序的妥协或和解安排之下，该申请人所具有的权利(在该等权利关乎任何讼费或费用的范围内)。 (6)第(5)款所设定的押记，受《法律援助条例》(第91章)下的押记所规限，亦受该条例中关乎将任何款项付入根据该条例设立的法律援助辅助计划基金的条文所规限。 (7)在本条中——《法院规则》 (relevant rules)指根据《区域法院条例》(第336章)订立的规则； 答辩人(respondent)包括将会成为答辩人的人。 (由 2012年第18号第39条增补)", "66B. Commissioner may grant assistance in respect of proceedings (1) A person who may institute proceedings to seek compensation under section 66 may make an application to the Commissioner for assistance in respect of those proceedings. (2) The Commissioner must consider an application under subsection (1) and may grant it if the Commissioner thinks fit to do so, in particular if— (a) the case raises a question of principle; or (b) it is unreasonable, having regard to the complexity of the case or the applicant’s position in relation to the respondent or another person involved or any other matter, to expect the applicant to deal with the case unaided. (3) Assistance by the Commissioner under this section may include— (a) giving advice; (b) arranging for the giving of advice or assistance by a solicitor or counsel; (c) arranging for representation by any person, including all such assistance as is usually given by a solicitor or counsel in the steps preliminary or incidental to any proceedings, or in arriving at or giving effect to a compromise to avoid or bring to an end any proceedings; and (d) any other form of assistance which the Commissioner may consider appropriate. (4) Subsection (3)(c) does not affect the law and practice regulating the descriptions of persons who may appear in, conduct, defend and address a court in, any proceedings except to the extent permitted ..."),
  source-statutes-cell("程序性补充条款（执行/调查衔接）：确保调查结果能接上后续执法动作。"),

  "s.66D",
  source-statutes-dual-cell("66D. 专员要求提供材料及协助的权力(1)如专员就某项指明调查，合理地怀疑某人——(a)管有或控制(或可能管有或控制)与该项调查相关的材料；或(b)可能在其他方面有能力就该项调查协助专员， 则本条适用。 (2)专员可藉向上述的人发出书面通知，要求该人——(a)凡专员合理地相信，某事宜(相干事宜)与有关指明调查相关——向专员提供该人管有或控制的、关乎相干事宜的材料； (b)在指明的时间及地点，面见专员，并回答关乎相干事宜的问题； (c)回答关乎相干事宜的书面问题； (d)作出关乎相干事宜的陈述；或(e)向专员提供专员为该项指明调查而合理地要求的所有协助。 (3)第(2)款所指的通知， 须——(a)符合指明格式； (b)由专员或订明人员签署；及(c)示明有关指明调查之标的事宜及目的。 (4)专员亦可在上述通知内，指明——(a)有关材料须于何时何地提供；及(b)该材料须以何种方式及形式提供。 (5)根据第(2)(a)款要求某人提供材料的权力，包括要求以下事宜的权力——(a)如该材料并非以可阅读形式记录——以符合下述说明的形式，交出该材料的复本——(i)属可见及可阅读形式；或(ii)能够轻易地以可见及可阅读形式从其中产生该复本的形式；及(b)如该材料以电子形式储存——该人作出以下事情——(i)就操作载有该材料的设备，给予指示；及(ii)提供适当系统，以将该材料转为纸上书面形式。 (6)根据第(2)(a)款要求某人提供材料的权力，包括作出以下作为的权力——(a) (如该人有提供该材料)采取以下行动——(i)复制该材料，或摘录其内容； (ii)在为有关指明调查而合理所需的期间内，保留该材料；或(iii)要求该人，或要求专员合理地相信能够给予关于该材料的解释或进一步详情的另一人，给予关于该材料的解释或进一步详情；及(b) (如该人没有提供该材料)要求该人(尽其所知所信)述明该材料在何处。 (7)如专员根据第(2)(a)款行使权力，要求某人向专员提供电子器材，该权力只可在第66G条的规限下行使。", "66D. Commissioner’s powers to require materials and assistance (1) This section applies if the Commissioner reasonably suspects that, in relation to a specified investigation, a person— (a) has or may have possession or control of any material relevant to that investigation; or (b) may otherwise be able to assist the Commissioner in relation to that investigation. (2) The Commissioner may, by written notice given to the person, require the person— (a) to provide the Commissioner with any material in the person’s possession or control relating to a matter that the Commissioner reasonably believes to be relevant to the specified investigation; (b) to attend before the Commissioner at a specified time and place, and answer any question relating to a matter that the Commissioner reasonably believes to be relevant to the specified investigation; (c) to answer any written question relating to a matter that the Commissioner reasonably believes to be relevant to the specified investigation; (d) to make a statement relating to a matter that the Commissioner reasonably believes to be relevant to the specified investigation; or (e) to give the Commissioner all the assistance that the Commissioner reasonably requires for the specified investigation. (3) A notice under subsection (2) must— (a) be in the specified form; (b) be signed by the Commissioner or a prescribed officer; and (c) in..."),
  source-statutes-cell("程序性补充条款（含时限/形式）：逾期或格式不符都可能影响效力。"),

  "s.66K",
  source-statutes-dual-cell("66K. 标的披露的涵义(1)就本分部而言，凡某人(披露者)在以下情况下披露资料当事人的个人资料(不论是否在香港披露)，则该项披露即属标的披露——(a)在该项披露作出时，该当事人——(i)属香港居民；或(ii)身处香港；及(b)披露者在未获该当事人的相关同意下，披露上述个人资料， 而——(i)披露者的意图，是导致该当事人或其任何家人蒙受任何指明伤害；或(ii)披露者罔顾是否会(或相当可能会)导致该当事人或其任何家人蒙受任何指明伤害。 (2)在本条中——指明伤害(specified harm)具有第64(6)条所给予的涵义； 相关同意(relevant consent)具有第64(6)条所给予的涵义。", "66K. Meaning of subject disclosure (1) For the purposes of this Division, a disclosure (whether or not in Hong Kong) of personal data of a data subject by a person is a subject disclosure if— (a) when the disclosure is made, the data subject— (i) is a Hong Kong resident; or (ii) is present in Hong Kong; and (b) the person discloses the personal data without the relevant consent of the data subject— (i) with an intent to cause any specified harm to the data subject or any family member of the data subject; or (ii) being reckless as to whether any specified harm would be, or would likely be, caused to the data subject or any family member of the data subject. (2) In this section— relevant consent (相关同意) has the meaning given by section 64(6) ; specified harm (指明伤害) has the meaning given by section 64(6) ."),
  source-statutes-cell("程序性补充条款：用于衔接不同执法步骤，避免程序断层。"),

  "s.66M",
  source-statutes-dual-cell("66M. 送达停止披露通知(1)如专员有合理理由相信——(a)有标的讯息存在；及(b)某名香港人士有能力就该讯息采取停止披露行动(不论是否在香港采取)， 则专员可向该人送达书面通知，指示该人采取该停止披露行动。 (2)此外，如专员有合理理由相信——(a)有属电子讯息的标的讯息存在；及(b)某非港人服务提供者有能力就该讯息采取停止披露行动(不论是否在香港采取)， 则专员可向该提供者送达书面通知，指示该提供者采取该停止披露行动。 (3)停止披露通知须——(a)述明第(1)或(2)款所述的专员相信之事，以及专员相信该事所据的理由； (b)在合理地切实可行的范围内，透过足以使有关停止披露行动得以采取的方式，示明有关标的讯息； (c)指明须采取的停止披露行动； (d)指明须于何日或之前采取该停止披露行动；及(e)附有本条及第66N 及 66O条的文本。 (4)专员可藉向获送达停止披露通知的人送达书面通知，撤销该停止披露通知。 (5)在本条中——非港人服务提供者(non-Hong Kong service provider)指已经或正在向任何香港人士提供服务的人(并非香港人士者)，不论服务是否在香港提供； 香港人士(Hong Kong person)指——(a)身处香港的个人；或(b)符合以下说明的团体——(i)在香港成立为法团、设立或注册；或(ii)在香港有业务地点。", "66M. Service of cessation notice (1) If the Commissioner has reasonable ground to believe that— (a) there is a subject message; and (b) a Hong Kong person is able to take a cessation action (whether or not in Hong Kong) in relation to the message, the Commissioner may serve a written notice on the person directing the person to take the cessation action. (2) In addition, if the Commissioner has reasonable ground to believe that— (a) there is a subject message that is an electronic message; and (b) a non-Hong Kong service provider is able to take a cessation action (whether or not in Hong Kong) in relation to the message, the Commissioner may serve a written notice on the provider directing the provider to take the cessation action. (3) The cessation notice must— (a) state the Commissioner’s belief mentioned in subsection (1) or (2) and the ground for that belief; (b) identify, in so far as reasonably practicable, the subject message in a way that is sufficient to enable the cessation action to be taken; (c) specify the cessation action that must be taken; (d) specify the date on or before which the cessation action must be taken; and (e) be accompanied by a copy of this section and sections 66N and 66O . (4) The Commissioner may cancel a cessation notice by serving a written notice on the person on whom the cessation notice is served. (5) In this section— Hong Kong person (香..."),
  source-statutes-cell("程序性补充条款：处理程序尾段的补强安排。"),

)
