#import "../preamble.typ": source-statutes-plus-table, source-statutes-cell, source-statutes-dual-cell, h2
#h2([C. Patents Ordinance (Cap.514)])
#source-statutes-plus-table(
  [*Section*],
  [*Text*],
  [*Notes*],

  "s.11A",
  source-statutes-dual-cell("11A. 不具损害性的披露(1)凡某项发明属一项转录标准专利申请的标的，为施行第9B条 ，如该项发明的披露符合第(2)款指明的条件，则在决定该项发明是否构成现有技术的一部分时，该项披露不予考虑。 (2)有关条件是——(a)上述披露，在转录标准专利申请的当作提交日期前6个月内发生；及(b)该项披露是以下事情所造成，或属以下事情的后果——(i)与申请人或该项发明当其时的所有人有关的明显滥用；或(ii)该申请人或该项发明当其时的所有人，已在某一订明的展览或会议上，展示该项发明。 (3)第(2)(b)(ii)款只在以下情况下适用——(a)在上述申请人提交相应指定专利申请时，已按照指定专利当局关乎不具损害性的披露的法律，述明上述发明已予如此展示；及(b)根据第15(2)(f)条的指定专利申请的记录请求，载有一项陈述，表示关乎上述披露的订明详情。", "11A. Non-prejudicial disclosure (1) For the purposes of section 9B , if the conditions specified in subsection (2) are satisfied, a disclosure of an invention that is the subject of a standard patent (R) application is not to be taken into consideration in determining whether the invention forms part of the state of the art. (2) The conditions are— (a) the disclosure occurred no earlier than 6 months before the deemed date of filing of the standard patent (R) application; and (b) the disclosure was due to, or in consequence of— (i) an evident abuse in relation to the applicant or a proprietor of the invention for the time being; or (ii) the fact that the applicant or a proprietor of the invention for the time being had displayed the invention at a prescribed exhibition or meeting. (3) Subsection (2)(b)(ii) applies only if— (a) at the time of filing the corresponding designated patent application, the applicant stated, in accordance with the law of the designated patent office relating to non-prejudicial disclosure, that the invention had been so displayed; and (b) the request to record the designated patent application contains a statement that indicates the prescribed details relating to the disclosure, as required under section 15(2)(f) ."),
  source-statutes-cell("某些先期披露可豁免，不当然破坏新颖性。"),

  "s.15",
  source-statutes-dual-cell("15. 记录请求的提交(1)根据第12(1)条有权就一项发明申请批予转录标准专利的任何人，可于自发表就该项发明而在指定专利当局提出的专利申请的日期后6个月内的任何时间，请求处长将该项指定专利申请的纪录记入注册纪录册内(在本条例中称为记录请求)。 (由 2016年第17号第21条修订) (2)每一上述请求须由申请人签署和以订明方式向处长提交，并须载有以下各项——(a)一份已发表的指定专利申请的影印本，包括与该指定专利申请一并发表的任何说明、权利要求、绘图、查检报告或撮录； (b)凡指定专利申请书并无载有任何作为发明人的人的姓名或名称，则一项识别申请人所相信是发明人的人或人等的陈述； (c)提出该项请求的人的姓名或名称及地址； (d)如提交请求的人并非是在指定专利申请中指名为申请人的人，则一项解释他有权就有关发明申请批予转录标准专利的陈述以及支持该项陈述的订明文件； (由 2016年第17号第21条修订) (e)如根据第11B条声称具有优先权，而该优先权是基于该条所述的较早申请而在指定专利当局享有的，则须载有一项显示以下细节的陈述——(由 2001年第2号第3条修订；由 2016年第17号第21条修订) (i)声称具有优先权的日期； (ii)提交该项较早申请书的所在国家； (f)如在提交指定专利申请时已按照指定专利当局的法律就有关发明过往所作的披露提出权利要求，而该项披露就指定专利当局的法律而言属不具损害性的披露，则须载有一项显示关乎该项过往的披露的订明细节的陈述；及(由 2001年第2号第3条代替) (g)在香港供送达文件用的地址。 (3)每一上述请求亦须符合本条例就以一种法定语文或兼以两种法定语文提供资料或将文件翻译成一种或两种法定语文的译本所订的规定。 (4)提交费及公告费须在最早向处长提交记录请求的任何部分后的1个月内予以缴付；如该两项费用的任何一项没有在该期限内或在根据第(5)款容许的较长期限内缴付，则转录标准专利的申请须当作被撤回。 (由 2016年第17号第21条修订) (5)规则可就未有在第(4)款所指明的时限内缴付提交费或公告费给予宽限期一事作出规定，使该等费用在宽限期内仍可有效地缴付。 (6)就在根据第8条指定有关的指定专利当局的日期前发表的指定专利申请而言，第(1)款并不适用。 (7)本条不阻止任何记录请求藉符合第17条规定的文件而提出。 [比照 EPC Art. 78；1977 c. 37 s. 14 U.K.]", "15. Filing of request to record (1) A person entitled under section 12(1) to apply for the grant of a standard patent (R) for an invention may, at any time within 6 months after the date of publication of an application in a designated patent office for a patent for the invention, request the Registrar to enter a record of that designated patent application in the register (in this Ordinance referred to as a request to record). (Amended 17 of 2016 s. 21) (2) Every such request shall be signed by the applicant and be filed with the Registrar in the prescribed manner and shall contain— (a) a photocopy of the designated patent application as published, that is to say, including any description, claims, drawings, search report or abstract published together with the designated patent application; (b) where the designated patent application does not contain the name of any person as being the inventor, a statement identifying the person or persons whom the applicant believes to be the inventor or inventors; (c) the name and address of the person making the request; (d) where the person filing the request is a person other than the person named as applicant in the designated patent application, a statement explaining his entitlement to apply for the grant of a standard patent (R) for the invention and prescribed documents supporting that statement; (Amended 17 of 2016 s. 21) (e) w..."),
  source-statutes-cell("提交记录请求的时间窗、材料和费用规则在这里。"),

  "s.2",
  source-statutes-dual-cell("2. 释义(1)在本条例中，除文意另有所指外——不具损害性的披露(non-prejudicial disclosure)就一项发明而言，指该发明的披露，而就决定该发明是否属现有技术的一部分而言，该披露不在考虑之列； 反对或撤销专利的法律程序(opposition or revocation proceedings)就指定专利而言，指根据指定专利当局的法律进行的法律程序，而该法律有就在批予专利后的指明期限内撤销或修订指定专利之事作出规定； 《巴黎公约》 (Paris Convention)指1883年3月20日在巴黎签订并经不时修改或修订的《保护工业产权公约》； (由 2001年第2号第2条修订)巴黎公约国(Paris Convention country)指——(a)当其时在附表1 指明为已加入《巴黎公约》的任何国家； (b)受依据(a)段而在附表1 指明的任何国家的权限所管辖或以任何该等国家为宗主国的地区或地方，或由任何该等国家管治的地区或地方，而该等国家已代该地区或地方加入《巴黎公约》； 《日内瓦议定书》 (Protocol)指世界贸易组织总理事会于2005年12月6日在日内瓦通过的修订《知识产权协议》的议定书、该议定书的附件、《知识产权协议》的附件及该附件的附录； (由 2007年第21号第3条增补)世界贸易组织(WTO)指于1995年1月1日在日内瓦根据《世界贸易组织协议》设立的世界贸易组织； (由 2007年第21号第3条增补)世界贸易组织成员国、地区或地方(WTO member country, territory or area)指当其时在附表1 指明为已加入《世界贸易组织协议》的任何国家、地区或地方； 《世界贸易组织协议》 (World Trade Organisation Agreement)指1994年在马拉喀什订立并经不时修改或修订的以该名称为名的协议； (由 2001年第2号第2条修订)出口成员地(exporting member)指按照《总理事会决定》或《日内瓦议定书》制造供出口至合资格进口成员地的专利药剂制品的世界贸易组织成员国、地区或地方； (由 2007年第21号第3条增补)合资格进口成员地(eligible importing member)指——(a)获联合国承认为属最低度发展国家的世界贸易组织成员国、地区或地方；或(b)已就拟按照《总理事会决定》或《日内瓦议定书》进口药剂制品一事向知识产权理事会给予书面通知的任何其他世界贸易组织成员国、地区或地方； (由 2007年第21号第3条增补) 《多哈宣言》 (Doha Declaration)指世界贸易组织第四次部长级会议于2001年11月14日在卡塔尔的多哈通过的《与贸易有关的知识产权协议及公共卫生宣言》； (由 2007年第21号第3条增补)有关文书或法例(relevant instrument or legislation)指——(a) 《总理事会决定》； (b) 《日内瓦议定书》；或(c)出口成员地或合资格进口成员地(视属何情况而定)依据下述决定或议定书或为落实下述决定或议定书而订立的法例——(i) 《总理事会决定》；或(ii) 《日内瓦议定书》； (由 2007年第21号第3条增补)受保护的布图设计(拓朴图) (protected layout-desi...", "2. Interpretation (1) In this Ordinance, unless the context otherwise requires— application for a patent (专利的申请) and patent application (专利申请) mean— (a) an application for a standard patent (R); (b) an application for a standard patent (O); or (c) an application for a short-term patent; (Added 17 of 2016 s. 5) application for a patent or other protection (专利或其他保护的申请) means an application for any of the following— (a) a patent; (b) the registration of a utility model; (c) a utility certificate; (d) an inventor’s certificate; (Added 17 of 2016 s. 5) application for a short-term patent (短期专利的申请) and short-term patent application (短期专利申请) mean an application under Part 15 for a short-term patent; (Added 17 of 2016 s. 5) application for a standard patent (标准专利的申请) and standard patent application (标准专利申请) mean— (a) an application for a standard patent (R); or (b) an application for a standard patent (O); (Added 17 of 2016 s. 5) application for a standard patent (O) (原授标准专利的申请) and standard patent (O) application (原授标准专利申请) mean an application under Part 3 for a standard patent (O); (Added 17 of 2016 s. 5) certificate of substantive examination (实质审查证明书) means a certificate issued by the Registrar under section 127F in respect of a short-term patent; (Added 17 of 2016 s. 5) court (法院) means the Court of First Instance; (Amended 25 of 1998 s. 2) date of filing (提交日期)— (a) in relatio..."),
  source-statutes-cell("全条例定义入口。先看术语，再看权利义务。"),

  "s.37C",
  source-statutes-dual-cell("37C. 优先权利(1)如任何人已就一项发明提交——(a)一项非香港申请；或(b)一项香港申请， 则第(2)款适用。 (2)在符合订明条件的前提下，上述的人或其所有权继承人，在由最先非香港申请或香港申请的提交日期后的12个月内，就为同一发明而于其后提交的原授标准专利申请而言，享有优先权利。 (3)为施行第(2)款——(a)在某地方或为某地方提交每项非香港申请，如根据该地方的法例或根据有关双边或多边协议，属相等于正规国家提交，则须获承认为产生优先权利； (b)如某项其后的非香港申请(后者)的标的事项，与一项过往的最先非香港申请(前者)的标的事项相同，且在同一地方或为同一地方提交，则只有在符合以下条件的前提下——(i)在后者的提交日期，前者已在没有公开予公众查阅和没有留下任何有待解决的权利的情况下，被撤回、放弃或拒绝；及(ii)在该日期，前者没有被用作为声称具有优先权利的根据， 后者方就决定优先权而言，视作最先申请；及(c)如某项其后的非香港申请因(b)段，被视作最先申请，则前者此后不可用作为声称具有优先权利的根据。 (4)为施行第(2)款——(a)每项香港申请的正规提交，须获承认为产生优先权利； (b)如某项其后的香港申请(后者)的标的事项，与一项过往的最先香港申请(前者)的标的事项相同，则只有在符合以下条件的前提下——(i)在后者的提交日期，前者已在没有公开予公众查阅和没有留下任何有待解决的权利的情况下，被撤回、放弃或拒绝；及(ii)在该日期，前者没有被用作为声称具有优先权利的根据， 后者方就决定优先权而言，视作最先申请；及(c)如某项其后的香港申请因(b)段，被视作最先申请，则前者此后不可用作为声称具有优先权利的根据。 (5)凡因一项发明的非香港申请或香港申请，而产生某项优先权利，则该项优先权利的转让或以其他方式作出的转传，可连同该项申请进行，亦可独立地进行，而在第(2)款中提述某人的所有权继承人，须据此解释。 (6)在本条中——正规国家提交(regular national filing)指一项申请的提交，而该项提交确立该项申请提交的日期(不论该项申请的结果如何)； 香港申请的正规提交(regular filing of a Hong Kong application)指一项香港申请的提交，而该项提交确立该项申请提交的日期(不论该项申请的结果如何)。", "37C. Priority right (1) Subsection (2) applies if a person has filed— (a) a non-Hong Kong application for an invention; or (b) a Hong Kong application for an invention. (2) The person or the person’s successor in title enjoys, for the purpose of filing a subsequent standard patent (O) application for the same invention, a right of priority for the period of 12 months after the date of filing of the first non-Hong Kong application or Hong Kong application, subject to compliance with the prescribed conditions. (3) For the purposes of subsection (2)— (a) every filing of a non-Hong Kong application that is equivalent to a regular national filing under the domestic legislation of the place in or for which the application is filed, or under bilateral or multilateral agreements, is to be recognized as giving rise to a right of priority; (b) a subsequent non- Hong Kong application for the same subject- matter as in a previous first non- Hong Kong application and filed in or for the same place is to be considered as the first application for the purpose of determining priority only if, on the date of filing the subsequent application, the previous application— (i) has been withdrawn, abandoned or refused, without being open to public inspection and without leaving any rights outstanding; and (ii) has not served as a basis for claiming a right of priority; and (c) if, because of parag..."),
  source-statutes-cell("优先权条款：先申请先受益，但要满足期限和形式要求。"),

  "s.54",
  source-statutes-dual-cell("54. 专利与专利的申请的共同拥有权(1)凡某一专利是批予2人或多于2人的，除非有任何相反的协议，否则他们每人须享有在该专利中相等的不分割份数。 (2)凡有2人或多于2人为某一专利的所有人，则在符合本条的规定下及除任何协议已有相反规定外，他们每人均有权由其本人或其代理人为其本身的利益与在没有其他人同意亦无需向其他所有人交代的情况下，就有关发明作出任何若非因本款以及第68 及 69条的规定便会构成侵犯有关专利的作为；而任何该等作为不构成对有关专利的侵犯。 (3)除第13 、 37H 、 37I 、 37J 及 55条另有规定外及除当其时有效的任何协议另有规定外，凡有2人或多于2人为某一专利的所有人，他们其中一人不得在没有得到另一人或其余的人的同意下——(由 2016年第17号第57条修订) (a)申请修订该项专利的说明书，或申请撤销该项专利；或(b)批予在该项专利下的特许，或将该项专利中的份额转让或按揭。 (由 2016年第17号第57条修订) (4)除该等条文另有规定外，凡有2人或多于2人为某一专利的所有人，任何其他人均可向该等人士的其中一人提供与该项发明的任何重要因素有关的方法，以令该项发明发挥效用，而凭借本款提供此等方法并不构成对该专利的侵犯。 (由 2016年第17号第57条修订) (5)凡专利产品是由2名或多于2名所有人中的任何一名所有人处置而转予任何人的，则该人或透过该人提出申索的任何其他人须有权以同一方法处理该产品，犹如该产品已由唯一的注册所有人处置一样。 (6)第(1)或(2)款不影响受讬人或死者的遗产代理人的相互权利或义务，或他们作为受讬人或遗产代理人的权利或义务。 (7)本条须就所提交的专利的申请而具有效力，一如本条就专利而具有效力， 而——(a)凡提述某一专利和某一专利获批予，须据此分别包括提述任何该等申请和该等申请已予提交；及(b)在第(5)款中提述专利产品，须据此解释。 [比照 1977 c. 37 s. 36 U.K.； EPC Art. 59]", "54. Co-ownership of patents and applications for patents (1) Where a patent is granted to 2 or more persons each of them shall, subject to any agreement to the contrary, be entitled to an equal undivided share in the patent. (2) Where 2 or more persons are proprietors of a patent, then, subject to this section and to any agreement to the contrary, each of them shall be entitled, by himself or his agent, to do in respect of the invention concerned, for his own benefit and without the consent of or the need to account to the other or others, any act which would apart from this subsection and sections 68 and 69 amount to an infringement of the patent concerned; and any such act shall not amount to an infringement of the patent concerned. (3) Subject to sections 13 , 37H , 37I , 37J and 55 and to any agreement for the time being in force, where 2 or more persons are proprietors of a patent one of them shall not without the consent of the other or others— (Amended 17 of 2016 s. 57) (a) make an application for amending the specification of the patent or for revoking the patent; or (b) grant a licence under the patent, or assign or mortgage a share in the patent. (Amended 17 of 2016 s. 57) (4) Subject to those sections, where 2 or more persons are proprietors of a patent, anyone else may supply one of those persons with the means, relating to an essential element of the invention, ..."),
  source-statutes-cell("专利共同共有时，谁能单独做什么、谁要先同意，在这里分配。"),

  "s.57",
  source-statutes-dual-cell("57. 就雇员的发明而享有的权利(1)即使在任何法律规则中另有规定，就本条例的目的和一切其他目的而言，一名雇员所作出的任何发明， 如——(a)是在该雇员的正常职务过程中作出的，或是在他的正常职务以外但属明确地指派予他的职务过程中作出的，且两者的情况均可使人合理地预期某项发明可从其职务的执行中产生；或(b)是在该雇员的职务过程中作出的，且在作出该项发明时，因其职务的性质以及因其职务的性质而产生的特定责任，该雇员有特殊义务促进其雇主的业务利益， 则该项发明在该雇员与其雇主之间须视为属于其雇主的。 (2)就上述目的而言，一名雇员所作出的任何其他发明，在该雇员与其雇主之间须视为属于该雇员的。 (3)凡任何发明在某一雇员与其雇主之间凭借本条而属于该雇员的， 则——(a)该雇员或其代表或藉着该雇员提出申索的任何人为谋求一项专利申请；或(b)任何人为实行或实施该项发明， 而作的任何事情，均不得视为侵犯关乎该项发明的任何模型或文件中的任何受保护的布图设计(拓朴图)的权利，而该权利在该雇员与其雇主之间是由其雇主所享有的。 [比照 1977 c. 37 s. 39 U.K.]", "57. Right to employees’ inventions (1) Notwithstanding anything in any rule of law, an invention made by an employee shall, as between him and his employer, be taken to belong to his employer for the purposes of this Ordinance and all other purposes if— (a) it was made in the course of the normal duties of the employee or in the course of duties falling outside his normal duties, but specifically assigned to him, and the circumstances in either case were such that an invention might reasonably be expected to result from the carrying out of his duties; or (b) the invention was made in the course of the duties of the employee and, at the time of making the invention, because of the nature of his duties and the particular responsibilities arising from the nature of his duties he had a special obligation to further the interests of the employer’s undertaking. (2) Any other invention made by an employee shall, as between him and his employer, be taken for those purposes to belong to the employee. (3) Where by virtue of this section an invention belongs, as between him and his employer, to an employee, nothing done— (a) by or on behalf of the employee or any person claiming under him for the purposes of pursuing an application for a patent; or (b) by any person for the purpose of performing or working the invention, shall be taken to infringe any protected layout- design (topograp..."),
  source-statutes-cell("职务发明归属规则：多数情形下雇主优先。"),

  "s.73",
  source-statutes-dual-cell("73. 防止直接使用发明任何专利在其有效时均授予其所有人权利以阻止所有未获他同意的第三者在香港作出以下全部或任何一项作为——(a)就任何属该专利的标的事项的产品而言——(i)制造、使用或进口该产品或将产品推出市场；或(ii)屯积该产品，而不论是为将该产品推出(在香港或其他地方的)市场的目的或为其他目的； (b)就任何属该专利的标的事项的方法而言——(i)使用该方法；或(ii)当第三者知道在没有该专利的所有人同意下而使用该方法是被禁止的，或在当时的情况下该项禁止对一个合理的人而言是明显的，但却提供该方法予人在香港使用； (c)凡该项发明为一个方法，则就藉该方法而直接获得的任何产品而言——(i)将该产品推出市场或使用或进口该产品；或(ii)屯积该产品，而不论是为将该产品推出(在香港或其他地方的)市场的目的或为其他目的。 [比照 1992 No. 1 s. 40 Eire]", "73. Prevention of direct use of invention A patent while it is in force shall confer on its proprietor the right to prevent all third parties not having his consent from doing in Hong Kong all or any of the following— (a) in relation to any product which is the subject- matter of the patent— (i) making, putting on the market, using or importing the product; or (ii) stocking the product, whether for the purpose of putting it on the market (in Hong Kong or elsewhere) or otherwise; (b) in relation to any process which is the subject- matter of the patent— (i) using the process; or (ii) offering the process for use in Hong Kong when the third party knows, or it is obvious to a reasonable person in the circumstances, that the use of the process is prohibited without the consent of the proprietor of the patent; (c) where the invention is a process, then in relation to any product obtained directly by means of that process— (i) putting on the market, using or importing the product; or (ii) stocking the product, whether for the purpose of putting it on the market (in Hong Kong or elsewhere) or otherwise. [cf. 1992 No. 1 s. 40 Eire]"),
  source-statutes-cell("专利权的“禁止他人实施”边界条款。"),

  "s.75",
  source-statutes-dual-cell("75. 对专利的效力的限制任何专利所授予的权利不得扩大至以下作为——(a)为非商业目的而私下作出的作为； (b)为实验目的而作出与有关专利发明的标的事项有关的作为； (c)按照注册医生或注册牙医开出的处方为个别病案在药房即时制备药物或与如此制备药物有关的作为(而注册医生及注册牙医两词分别具有《医生注册条例》(第161章)第2条和《牙医注册条例》(第156章)第2(1)条给予注册医生及注册牙医的涵义)； (d)当在任何巴黎公约国或世界贸易组织成员国、地区或地方(香港除外)注册的船只临时或意外地进入香港水域时——(由 2024年第21号第78条修订) (i)在该等船只上；或(ii)在该等船只的船身内，或其机械、滑车索具、传动装置或其他零件上， 使用属该专利的标的之发明，但该项发明须是专为该等船只的需要而在香港水域内使用的； (e)当巴黎公约国或世界贸易组织成员国、地区或地方(香港除外)的飞机、气垫船或陆上交通工具临时或意外地进入香港时——(i)在该等飞机、气垫船或陆上交通工具的构造或操作上；或(ii)在该等飞机、气垫船或陆上交通工具的零件的构造或操作上， 使用属该专利的标的之发明； (f)使用属《民航条例》(第448章)第10(4)条所适用的且已合法进入香港或正合法经过香港(包括香港上空及香港水域)的飞机，或为该等飞机而将该等飞机的任何部分或零件输入香港，或在香港使用或贮存该部分或零件。 (由 2024年第21号第78条修订) [比照 1992 No. 1 s. 42 Eire]", "75. Limitation of effect of patent The rights conferred by a patent shall not extend to— (a) acts done privately for non-commercial purposes; (b) acts done for experimental purposes relating to the subject-matter of the relevant patented invention; (c) the extemporaneous preparation for individual cases in a pharmacy of a medicine in accordance with a medical prescription issued by a registered medical practitioner or registered dentist (which terms bear the meaning assigned to them by section 2 of the Medical Registration Ordinance (Cap. 161) and section 2(1) of the Dentists Registration Ordinance (Cap. 156) respectively) or acts concerning the medicine so prepared; (d) the use of the invention which is the subject of the patent— (i) on board vessels registered in any of the Paris Convention countries or WTO member countries, territories or areas, other than Hong Kong; or (ii) in the body of such vessels, or in the machinery, tackle, gear or other accessories of such vessels, when such vessels temporarily or accidentally enter the waters of Hong Kong, but only if the invention is used in such waters exclusively for the needs of the vessel; (Amended 21 of 2024 s. 78) (e) the use of the invention which is the subject of the patent in the construction or operation of— (i) aircraft, hovercraft or land vehicles of Paris Convention countries or WTO member countries, territories o..."),
  source-statutes-cell("专利限制与例外：私人、实验、处方等场景可豁免。"),

  "s.9A",
  source-statutes-dual-cell("9A. 可享专利发明(1)任何发明如——(a)是新颖的； (b)包含创造性；及(c)能作工业应用， 即属可享专利。 (2)以下项目不得视作第(1)款所指的发明——(a)发现、科学理论或数学方法； (b)美学上的创作； (c)用以实行智力活动、进行游戏或进行业务的计划、规则或方法，或用于电脑的程式；及(d)呈示资料。 (3)第(2)款只在任何专利或专利申请与该款提述的标的事项或活动有关的范围内，豁除该事项或活动的可享专利性。 (4)就第(1)款而言，藉外科手术或治疗以医治人体或动物身体的方法，或施行于人体或动物身体的诊断方法，均不得视作能作工业应用的发明。然而，本款不适用于供在任何该等方法中使用的产品，尤其不适用于供在任何该等方法中使用的物质或合成物。 (5)凡某发明的公布或实施，是会违反公共秩序或道德的，该发明即不属一项可享专利发明。然而，任何发明的实施，不得只因其被在香港施行的任何法律所禁止，而视作违反公共秩序或道德。 (6)以下项目不属可享专利——(a)植物或动物品种；及(b)用作生产植物或动物的基本上属生物学的方法(微生学方法或其产品除外)。", "9A. Patentable inventions (1) An invention is patentable if it— (a) is new; (b) involves an inventive step; and (c) is susceptible of industrial application. (2) The following are not to be regarded as an invention for the purposes of subsection (1)— (a) a discovery, scientific theory or mathematical method; (b) an aesthetic creation; (c) a scheme, rule or method for performing a mental act, playing a game or doing business, or a program for a computer; and (d) a presentation of information. (3) Subsection (2) excludes the patentability of the subject-matter or activities referred to in that subsection only to the extent to which a patent or patent application relates to the subject-matter or activities as such. (4) A method for the treatment of the human or animal body by surgery or therapy, or a diagnostic method practised on the human or animal body, is not to be regarded as an invention that is susceptible of industrial application for the purposes of subsection (1). However, this subsection does not apply to a product, and in particular a substance or composition, for use in any such method. (5) An invention the publication or working of which would be contrary to public order (“ordre public”) or morality is not a patentable invention. However, the working of an invention is not to be regarded as so contrary only because it is prohibited by any law in force in Hong Kong..."),
  source-statutes-cell("可专利三要件：新颖性、创造性、工业应用。"),

  "s.9D",
  source-statutes-dual-cell("9D. 工业应用某项发明如能够在任何种类的工业(包括农业)中作出或使用，则须视作能作工业应用。", "9D. Industrial application An invention is to be regarded as susceptible of industrial application if it can be made or used in any kind of industry, including agriculture."),
  source-statutes-cell("工业应用要求：能在产业中制造或使用。"),

)